const adjectives = [
  { english: "unequaled", uzbek: "tengsiz" },
  { english: "inconclusive", uzbek: "noaniq" },
  { english: "yielding", uzbek: "xosil beruvchi" },
  { english: "slippery", uzbek: "sirg'anchiq" },
  { english: "agitated", uzbek: "xayajonlangan" },
  { english: "debonair", uzbek: "yomon" },
  { english: "icy", uzbek: "muzli" },
  { english: "madly", uzbek: "aqldan ozgan" },
  { english: "scarce", uzbek: "kam" },
  { english: "magenta", uzbek: "mjenta" },
  { english: "abortive", uzbek: "muvaffaquyatsiz" },
  { english: "absorbing", uzbek: "singdiruvchi" },
  { english: "sweet", uzbek: "shirin" },
  { english: "longing", uzbek: "sog'inish" },
  { english: "able", uzbek: "qodir" },
  { english: "rambunctious", uzbek: "shovshuvli" },
  { english: "macabre", uzbek: "daxshatli" },
  { english: "natural", uzbek: "tabiy" },
  { english: "ready", uzbek: "tayyor" },
  { english: "acoustic", uzbek: "tovush qay-gan" },
  { english: "mighty", uzbek: "qudratli" },
  { english: "disgusted", uzbek: "jirkanch" },
  { english: "bulky", uzbek: "katta" },
  { english: "bumpy", uzbek: "g'alati" },
  { english: "mean", uzbek: "anglatadi" },
  { english: "young", uzbek: "yosh" },
  { english: "narrow", uzbek: "tor" },
  { english: "painstaking", uzbek: "mashaqqatli" },
  { english: "shaky", uzbek: "titroqli" },
  { english: "sour", uzbek: "nordon" },
];
