const simples = [
    { "english": "that", "uzbek": "o'sha" },
    { "english": "there", "uzbek": "u yerda" },
    { "english": "their", "uzbek": "ularning" },
    { "english": "so", "uzbek": "shuning uchun" },
    { "english": "just", "uzbek": "shunchaki" },
    { "english": "him", "uzbek": "uni unga" },
    { "english": "take", "uzbek": "olmoq" },
    { "english": "into", "uzbek": "ichiga" },
    { "english": "them", "uzbek": "ularni/ ularga" },
    { "english": "than", "uzbek": "dan ko'ra" },
    { "english": "its", "uzbek": "uning" },
    { "english": "over", "uzbek": "ustida ustidan" },
    { "english": "also", "uzbek": "ham" },
    { "english": "how", "uzbek": "qanday" },
    { "english": "even", "uzbek": "hatto" },
    { "english": "these", "uzbek": "bular" },
    { "english": "give", "uzbek": "bermoq" },
    { "english": "most", "uzbek": "ko'p" },
    { "english": "us", "uzbek": "bizni / bizga" },
    { "english": "thing", "uzbek": "narsa" },
    { "english": "those", "uzbek": "o'sha narsalar" },
    { "english": "tell", "uzbek": "aytib bermoq" },
    { "english": "through", "uzbek": "orqali" },
    { "english": "may", "uzbek": "mumkin" },
    { "english": "should", "uzbek": "kerak" },
    { "english": "still", "uzbek": "hali ham" },
    { "english": "too", "uzbek": "ham" },
    { "english": "state", "uzbek": "davlat / holat" },
    { "english": "another", "uzbek": "yana bir" },
    { "english": "own", "uzbek": "o'z" },
    { "english": "put", "uzbek": "qo'ymoq" },
    { "english": "keep", "uzbek": "saqlamoq" },
    { "english": "let", "uzbek": "ruxsat bermoq" },
    { "english": "same", "uzbek": "xuddi o'sha" },
    { "english": "turn", "uzbek": "burilmoq navbat" },
    { "english": "might", "uzbek": "mumkin" },
    { "english": "such", "uzbek": "shunday" },
    { "english": "case", "uzbek": "holat" },
    { "english": "move", "uzbek": "harakatlanmoq" },
    { "english": "hold", "uzbek": "ulashmoq" },
    { "english": "bring", "uzbek": "olib ketmoq" },
    { "english": "happen", "uzbek": "sodir bo'lmoq" },
    { "english": "without", "uzbek": "siz" },
]
