const simples = [
    { "english": "pass", "uzbek": "o‘tmoq" },
    { "english": "white", "uzbek": "oq" },
    { "english": "least", "uzbek": "eng kam" },
    { "english": "president", "uzbek": "prezident" },
    { "english": "learn", "uzbek": "o‘rganmoq" },
    { "english": "real", "uzbek": "haqiqiy" },
    { "english": "change", "uzbek": "o‘zgartirmoq" },
    { "english": "team", "uzbek": "jamoa" },
    { "english": "minute", "uzbek": "daqiqа" },
    { "english": "best", "uzbek": "eng yaxshi" },
    { "english": "several", "uzbek": "bir nechta" },
    { "english": "idea", "uzbek": "g‘oya" },
    { "english": "kid", "uzbek": "bola" },
    { "english": "body", "uzbek": "tana" },
    { "english": "information", "uzbek": "ma’lumot" },
    { "english": "nothing", "uzbek": "hech narsa" },
    { "english": "ago", "uzbek": "oldin" },
    { "english": "lead", "uzbek": "yetaklamoq" },
    { "english": "social", "uzbek": "ijtimoiy" },
    { "english": "understand", "uzbek": "tushunmoq" },
    { "english": "whether", "uzbek": "yoki ... yo‘qmi" },
    { "english": "watch", "uzbek": "tomosha qilmoq" },
    { "english": "together", "uzbek": "birgalikda" },
    { "english": "follow", "uzbek": "ergashmoq" },
    { "english": "around", "uzbek": "atrofida" },
    { "english": "parent", "uzbek": "ota-ona" },
    { "english": "only", "uzbek": "gina" },
    { "english": "stop", "uzbek": "to‘xtamoq" },
    { "english": "face", "uzbek": "to‘qnashmoq" },
    { "english": "anything", "uzbek": "biror narsa" },
    { "english": "create", "uzbek": "yaratmoq" },
    { "english": "public", "uzbek": "ommaviy" },
    { "english": "already", "uzbek": "allaqachon" },
    { "english": "speak", "uzbek": "gapirmoq" },
    { "english": "others", "uzbek": "boshqalar" },
    { "english": "read", "uzbek": "o‘qimoq" },
    { "english": "level", "uzbek": "daraja" },
    { "english": "allow", "uzbek": "ruxsat bermoq" },
    { "english": "office", "uzbek": "ofis" },
    { "english": "spend", "uzbek": "sarflamoq" },
    { "english": "door", "uzbek": "eshik" },
    { "english": "health", "uzbek": "sog‘liq" },
    { "english": "person", "uzbek": "shaxs" },
    { "english": "art", "uzbek": "san’at" },
    { "english": "sure", "uzbek": "ishonchli" },
    { "english": "such", "uzbek": "bunday" },
    { "english": "war", "uzbek": "urush" },
    { "english": "history", "uzbek": "tarix" },
    { "english": "party", "uzbek": "partiya / ziyofat" },
    { "english": "within", "uzbek": "ichida" },
    { "english": "grow", "uzbek": "o‘smoq" },
    { "english": "result", "uzbek": "natija" },
    { "english": "open", "uzbek": "ochmoq" },
    { "english": "morning", "uzbek": "ertalab" },
    { "english": "walk", "uzbek": "yurmoq" },
    { "english": "reason", "uzbek": "sabab" },
    { "english": "low", "uzbek": "past" },
    { "english": "win", "uzbek": "yutmoq" },
    { "english": "research", "uzbek": "tadqiqot" },
    { "english": "girl", "uzbek": "qiz" },
    { "english": "guy", "uzbek": "yigit" },
    { "english": "early", "uzbek": "erta" },
    { "english": "food", "uzbek": "ovqat" },
    { "english": "before", "uzbek": "oldin" },
    { "english": "moment", "uzbek": "lahza" },
    { "english": "himself", "uzbek": "o‘zi (erkak)" },
    { "english": "air", "uzbek": "havo" },
    { "english": "teacher", "uzbek": "o‘qituvchi" },
    { "english": "force", "uzbek": "kuch" },
    { "english": "offer", "uzbek": "taklif qilmoq" },
    { "english": "enough", "uzbek": "yetarli" },
    { "english": "both", "uzbek": "ikkalasi ham" },
    { "english": "education", "uzbek": "ta’lim" },
    { "english": "across", "uzbek": "kesib o‘tib" },
    { "english": "although", "uzbek": "garchi" },
    { "english": "remember", "uzbek": "eslamoq" },
    { "english": "foot", "uzbek": "oyoq" },
    { "english": "second", "uzbek": "ikkinchi" },
    { "english": "boy", "uzbek": "o‘g‘il bola" },
    { "english": "maybe", "uzbek": "balki" },
    { "english": "toward", "uzbek": "tomon" },
    { "english": "able", "uzbek": "qodir" },
    { "english": "age", "uzbek": "yosh" },
    { "english": "off", "uzbek": "o‘chirilgan" },
    { "english": "policy", "uzbek": "siyosat" },
    { "english": "everything", "uzbek": "hamma narsa" },
    { "english": "love", "uzbek": "sevgi / sevmok" },
    { "english": "process", "uzbek": "jarayon" },
    { "english": "music", "uzbek": "musiqa" },
    { "english": "including", "uzbek": "jumladan" },
    { "english": "consider", "uzbek": "hisoblamoq" },
    { "english": "appear", "uzbek": "paydo bo‘lmoq" },
    { "english": "actually", "uzbek": "aslida" },
    { "english": "buy", "uzbek": "sotib olmoq" },
    { "english": "probably", "uzbek": "ehtimol" },
    { "english": "human", "uzbek": "inson" },
    { "english": "wait", "uzbek": "kutmoq" },
    { "english": "serve", "uzbek": "xizmat qilmoq" },
    { "english": "market", "uzbek": "bozor" },
    { "english": "die", "uzbek": "o‘lmoq" },
    { "english": "send", "uzbek": "yubormoq" },
    { "english": "expect", "uzbek": "kutilmoq" },
    { "english": "sense", "uzbek": "ma’no / sezgi" },
    { "english": "build", "uzbek": "qurmoq" },
    { "english": "stay", "uzbek": "qolmoq" },
    { "english": "fall", "uzbek": "yiqilmoq" },
    { "english": "oh", "uzbek": "voy" },
    { "english": "nation", "uzbek": "millat" },
    { "english": "plan", "uzbek": "reja" },
    { "english": "cut", "uzbek": "kesmoq" },
    { "english": "college", "uzbek": "kollej" },
    { "english": "interest", "uzbek": "qiziqish" },
    { "english": "death", "uzbek": "o‘lim" },
    { "english": "course", "uzbek": "kurs" },
    { "english": "someone", "uzbek": "kimdir" },
    { "english": "experience", "uzbek": "tajriba" },
    { "english": "behind", "uzbek": "orqada" },
    { "english": "reach", "uzbek": "yetib bormoq" },
    { "english": "local", "uzbek": "mahalliy" },
    { "english": "kill", "uzbek": "o‘ldirmoq" },
    { "english": "six", "uzbek": "olti" },
    { "english": "remain", "uzbek": "qolmoq" },
    { "english": "effect", "uzbek": "ta’sir" },
    { "english": "yeah", "uzbek": "ha (norasmiy)" },
    { "english": "suggest", "uzbek": "taklif qilmoq" },
    { "english": "class", "uzbek": "sinf" },
    { "english": "control", "uzbek": "nazorat" },
    { "english": "raise", "uzbek": "ko‘tarmoq" },
    { "english": "care", "uzbek": "g‘amxo‘rlik" },
    { "english": "perhaps", "uzbek": "balki" },
    { "english": "little", "uzbek": "ozgina" },
    { "english": "late", "uzbek": "kech" },
    { "english": "hard", "uzbek": "qiyin" },
    { "english": "field", "uzbek": "maydon" },
    { "english": "else", "uzbek": "yana / boshqa" },
    { "english": "pass", "uzbek": "bermoq / o‘tmoq" },
    { "english": "former", "uzbek": "sobiq" },
    { "english": "sell", "uzbek": "sotmoq" },
    { "english": "major", "uzbek": "asosiy" },
    { "english": "sometimes", "uzbek": "ba’zan" },
    { "english": "require", "uzbek": "talab qilmoq" },
    { "english": "along", "uzbek": "bo‘ylab" },
    { "english": "development", "uzbek": "rivojlanish" },
    { "english": "themselves", "uzbek": "o‘zlari" },
    { "english": "report", "uzbek": "hisobot" },
    { "english": "role", "uzbek": "rol" },
    { "english": "better", "uzbek": "yaxshiroq" },
    { "english": "economic", "uzbek": "iqtisodiy" },
    { "english": "effort", "uzbek": "harakat" },
    { "english": "up", "uzbek": "yuqoriga" },
    { "english": "decide", "uzbek": "qaror qilmoq" },
    { "english": "rate", "uzbek": "daraja / tezlik" },
    { "english": "strong", "uzbek": "kuchli" },
    { "english": "possible", "uzbek": "mumkin" },
    { "english": "heart", "uzbek": "yurak" },
    { "english": "drug", "uzbek": "dori" },
    { "english": "show", "uzbek": "namoyish" },
    { "english": "leader", "uzbek": "yetakchi" },
    { "english": "light", "uzbek": "yorug‘lik" },
    { "english": "voice", "uzbek": "ovoz" },
    { "english": "wife", "uzbek": "xotin" },
    { "english": "whole", "uzbek": "butun" },
    { "english": "police", "uzbek": "politsiya" },
    { "english": "mind", "uzbek": "ong" },
    { "english": "finally", "uzbek": "nihoyat" },
    { "english": "pull", "uzbek": "tortmoq" },
    { "english": "return", "uzbek": "qaytmoq" }
]
