const simples = [
    { "english": "must", "uzbek": "kerak" },
    { "english": "home", "uzbek": "uy" },
    { "english": "under", "uzbek": "ostida" },
    { "english": "water", "uzbek": "suv" },
    { "english": "room", "uzbek": "xona" },
    { "english": "write", "uzbek": "yozmoq" },
    { "english": "mother", "uzbek": "ona" },
    { "english": "area", "uzbek": "hudud" },
    { "english": "national", "uzbek": "milliy" },
    { "english": "money", "uzbek": "pul" },
    { "english": "story", "uzbek": "hikoya" },
    { "english": "young", "uzbek": "yosh" },
    { "english": "fact", "uzbek": "fakt" },
    { "english": "month", "uzbek": "oy" },
    { "english": "different", "uzbek": "boshqa, farqli" },
    { "english": "lot", "uzbek": "ko‘p, juda ko‘p" },
    { "english": "study", "uzbek": "o‘qimoq, o‘rganmoq" },
    { "english": "book", "uzbek": "kitob" },
    { "english": "eye", "uzbek": "ko‘z" },
    { "english": "job", "uzbek": "ish" },
    { "english": "word", "uzbek": "so‘z" },
    { "english": "though", "uzbek": "garchi" },
    { "english": "business", "uzbek": "biznes" },
    { "english": "issue", "uzbek": "muammo, masala" },
    { "english": "side", "uzbek": "tomon" },
    { "english": "kind", "uzbek": "tur, xildagi" },
    { "english": "four", "uzbek": "to‘rt" },
    { "english": "head", "uzbek": "bosh" },
    { "english": "far", "uzbek": "uzoq" },
    { "english": "black", "uzbek": "qora" },
    { "english": "long", "uzbek": "uzun" },
    { "english": "both", "uzbek": "ikkalasi ham" },
    { "english": "little", "uzbek": "kichkina, ozgina" },
    { "english": "house", "uzbek": "uy" },
    { "english": "yes", "uzbek": "ha" },
    { "english": "after", "uzbek": "keyin" },
    { "english": "since", "uzbek": "dan beri" },
    { "english": "long", "uzbek": "ko‘p vaqt" },
    { "english": "provide", "uzbek": "ta’minlamoq" },
    { "english": "service", "uzbek": "xizmat" },
    { "english": "around", "uzbek": "atrofida" },
    { "english": "friend", "uzbek": "do‘st" },
    { "english": "important", "uzbek": "muhim" },
    { "english": "father", "uzbek": "ota" },
    { "english": "sit", "uzbek": "o‘tirmoq" },
    { "english": "away", "uzbek": "uzoqlashib" },
    { "english": "until", "uzbek": "gacha" },
    { "english": "power", "uzbek": "kuch, hokimiyat" },
    { "english": "hour", "uzbek": "soat" },
    { "english": "game", "uzbek": "o‘yin" },
    { "english": "often", "uzbek": "tez-tez" },
    { "english": "yet", "uzbek": "hali" },
    { "english": "line", "uzbek": "chiziq, qator" },
    { "english": "political", "uzbek": "siyosiy" },
    { "english": "end", "uzbek": "oxir" },
    { "english": "among", "uzbek": "orasida" },
    { "english": "ever", "uzbek": "hech qachon, hech" },
    { "english": "stand", "uzbek": "turmoq" },
    { "english": "bad", "uzbek": "yomon" },
    { "english": "lose", "uzbek": "yo‘qotmoq, yutqazmoq" },
    { "english": "however", "uzbek": "biroq" },
    { "english": "member", "uzbek": "a’zo" },
    { "english": "pay", "uzbek": "to‘lamoq" },
    { "english": "law", "uzbek": "qonun" },
    { "english": "meet", "uzbek": "uchrashmoq" },
    { "english": "car", "uzbek": "mashina" },
    { "english": "city", "uzbek": "shahar" },
    { "english": "almost", "uzbek": "deyarli" },
    { "english": "include", "uzbek": "o‘z ichiga olmoq" },
    { "english": "continue", "uzbek": "davom ettirmoq" },
    { "english": "set", "uzbek": "o‘rnatmoq, to‘plam" },
    { "english": "later", "uzbek": "keyinroq" },
    { "english": "community", "uzbek": "jamiyat" },
    { "english": "much", "uzbek": "ko‘p" },
    { "english": "name", "uzbek": "ism" },
    { "english": "five", "uzbek": "besh" },
    { "english": "once", "uzbek": "bir marta" },
    { "english": "white", "uzbek": "oq" },
    { "english": "least", "uzbek": "eng kam" },
    { "english": "president", "uzbek": "prezident" },
    { "english": "learn", "uzbek": "o‘rganmoq" },
    { "english": "real", "uzbek": "haqiqiy" },
    { "english": "change", "uzbek": "o‘zgartirmoq" },
    { "english": "team", "uzbek": "jamoa" },
    { "english": "minute", "uzbek": "daqiqa" },
    { "english": "best", "uzbek": "eng yaxshi" },
    { "english": "several", "uzbek": "bir necha" },
    { "english": "idea", "uzbek": "g‘oya" },
    { "english": "kid", "uzbek": "bola" },
    { "english": "body", "uzbek": "tana" },
    { "english": "information", "uzbek": "ma’lumot" },
    { "english": "nothing", "uzbek": "hech narsa" },
    { "english": "ago", "uzbek": "oldin" },
    { "english": "right", "uzbek": "o‘ng/to‘g‘ri" },
    { "english": "lead", "uzbek": "yetaklamoq" },
    { "english": "social", "uzbek": "ijtimoiy" },
    { "english": "understand", "uzbek": "tushunmoq" },
    { "english": "whether", "uzbek": "yo‘qmi, -mi" },
    { "english": "back", "uzbek": "orqa" },
    { "english": "watch", "uzbek": "ko‘rmoq, soat" },
    { "english": "together", "uzbek": "birgalikda" },
    { "english": "follow", "uzbek": "ergashmoq" },
    { "english": "around", "uzbek": "atrofida" },
    { "english": "parent", "uzbek": "ota-ona" },
    { "english": "only", "uzbek": "faqat" },
    { "english": "stop", "uzbek": "to‘xtamoq" },
    { "english": "face", "uzbek": "yuz" },
    { "english": "anything", "uzbek": "nimadir" },
    { "english": "create", "uzbek": "yaratmoq" },
    { "english": "public", "uzbek": "ommaviy" },
    { "english": "already", "uzbek": "allaqachon" },
    { "english": "speak", "uzbek": "gapirmoq" },
    { "english": "others", "uzbek": "boshqalar" },
    { "english": "read", "uzbek": "o‘qimoq" },
    { "english": "level", "uzbek": "daraja" },
    { "english": "allow", "uzbek": "ruxsat bermoq" },
    { "english": "office", "uzbek": "ofis" },
    { "english": "spend", "uzbek": "sarflamoq" },
    { "english": "door", "uzbek": "eshik" },
    { "english": "health", "uzbek": "sog‘liq" },
    { "english": "person", "uzbek": "odam, shaxs" },
    { "english": "art", "uzbek": "san’at" },
    { "english": "sure", "uzbek": "ishonchli" },
    { "english": "such", "uzbek": "shunday" },
    { "english": "war", "uzbek": "urush" },
    { "english": "history", "uzbek": "tarix" },
    { "english": "party", "uzbek": "partiya, bazm" },
    { "english": "within", "uzbek": "ichida" },
    { "english": "grow", "uzbek": "o‘smoq" },
    { "english": "result", "uzbek": "natija" },
    { "english": "open", "uzbek": "ochmoq" },
    { "english": "morning", "uzbek": "ertalab" },
    { "english": "walk", "uzbek": "yurmoq" },
    { "english": "reason", "uzbek": "sabab" },
    { "english": "low", "uzbek": "past" },
    { "english": "win", "uzbek": "yutmoq" },
    { "english": "research", "uzbek": "tadqiqot" },
    { "english": "girl", "uzbek": "qiz bola" },
    { "english": "guy", "uzbek": "yigit" },
    { "english": "early", "uzbek": "erta" },
    { "english": "food", "uzbek": "ovqat" },
    { "english": "before", "uzbek": "oldin" },
    { "english": "moment", "uzbek": "lahza" },
    { "english": "air", "uzbek": "havo" },
    { "english": "teacher", "uzbek": "o‘qituvchi" },
    { "english": "force", "uzbek": "kuch" },
    { "english": "offer", "uzbek": "taklif qilmoq" },
    { "english": "enough", "uzbek": "yetarli" },
    { "english": "education", "uzbek": "ta’lim" },
    { "english": "across", "uzbek": "kesib o‘tib" },
    { "english": "although", "uzbek": "garchi" },
    { "english": "remember", "uzbek": "eslamoq" },
    { "english": "foot", "uzbek": "oyoq" },
    { "english": "second", "uzbek": "ikkinchi/soniya" },
    { "english": "boy", "uzbek": "o‘g‘il bola" },
    { "english": "maybe", "uzbek": "balki" },
    { "english": "toward", "uzbek": "tomonga" },
    { "english": "able", "uzbek": "qodir" },
    { "english": "age", "uzbek": "yosh" },
    { "english": "policy", "uzbek": "siyosat" },
    { "english": "everything", "uzbek": "hamma narsa" },
    { "english": "love", "uzbek": "sevgi/sevmoq" },
    { "english": "process", "uzbek": "jarayon" },
    { "english": "music", "uzbek": "musiqa" },
    { "english": "including", "uzbek": "jumladan" },
    { "english": "consider", "uzbek": "hisoblamoq, ko‘rib chiqmoq" },
    { "english": "appear", "uzbek": "paydo bo‘lmoq" },
    { "english": "actually", "uzbek": "aslida" },
    { "english": "buy", "uzbek": "sotib olmoq" },
    { "english": "probably", "uzbek": "ehtimol" },
    { "english": "human", "uzbek": "inson" },
    { "english": "wait", "uzbek": "kutmoq" },
    { "english": "serve", "uzbek": "xizmat qilmoq" },
    { "english": "market", "uzbek": "bozor" },
    { "english": "die", "uzbek": "o‘lmoq" },
    { "english": "send", "uzbek": "yubormoq" },
    { "english": "expect", "uzbek": "kutmoq" },
    { "english": "sense", "uzbek": "sezgi, ma’no" },
    { "english": "build", "uzbek": "qurmoq" },
    { "english": "stay", "uzbek": "qolmoq" },
    { "english": "fall", "uzbek": "yiqilmoq" },
    { "english": "oh", "uzbek": "voy, oh" },
    { "english": "nation", "uzbek": "millat" },
    { "english": "plan", "uzbek": "reja" },
    { "english": "cut", "uzbek": "kesmoq" },
    { "english": "college", "uzbek": "kollej" }
]
