const simples = [
    { "english": "free", "uzbek": "bepul / erkin" },
    { "english": "military", "uzbek": "harbiy" },
    { "english": "price", "uzbek": "narx" },
    { "english": "report", "uzbek": "hisobot" },
    { "english": "less", "uzbek": "kamroq" },
    { "english": "according", "uzbek": "ko‘ra" },
    { "english": "decision", "uzbek": "qaror" },
    { "english": "explain", "uzbek": "tushuntirmoq" },
    { "english": "son", "uzbek": "o‘g‘il" },
    { "english": "hope", "uzbek": "umid" },
    { "english": "develop", "uzbek": "rivojlanmoq" },
    { "english": "view", "uzbek": "qarash / manzara" },
    { "english": "relationship", "uzbek": "munosabat" },
    { "english": "carry", "uzbek": "ko‘tarmoq / olib yurmoq" },
    { "english": "town", "uzbek": "shahar" },
    { "english": "road", "uzbek": "yo‘l" },
    { "english": "drive", "uzbek": "haydamoq" },
    { "english": "arm", "uzbek": "qo‘l" },
    { "english": "true", "uzbek": "haqiqiy / rost" },
    { "english": "federal", "uzbek": "federal" },
    { "english": "break", "uzbek": "tanaffus / sindirmoq" },
    { "english": "better", "uzbek": "yaxshiroq" },
    { "english": "difference", "uzbek": "farq" },
    { "english": "thank", "uzbek": "rahmat aytmoq" },
    { "english": "receive", "uzbek": "qabul qilmoq" },
    { "english": "value", "uzbek": "qiymat" },
    { "english": "international", "uzbek": "xalqaro" },
    { "english": "building", "uzbek": "bino" },
    { "english": "action", "uzbek": "harakat" },
    { "english": "full", "uzbek": "to‘liq" },
    { "english": "model", "uzbek": "model / namuna" },
    { "english": "join", "uzbek": "qo‘shilmoq" },
    { "english": "season", "uzbek": "mavsum" },
    { "english": "society", "uzbek": "jamiyat" },
    { "english": "because", "uzbek": "chunki" },
    { "english": "tax", "uzbek": "soliq" },
    { "english": "director", "uzbek": "direktor" },
    { "english": "position", "uzbek": "lavozim / o‘rin" },
    { "english": "player", "uzbek": "o‘yinchi" },
    { "english": "agree", "uzbek": "rozi bo‘lmoq" },
    { "english": "especially", "uzbek": "ayniqsa" },
    { "english": "record", "uzbek": "yozuv / rekord" },
    { "english": "pick", "uzbek": "tanlamoq / uzmoq" },
    { "english": "wear", "uzbek": "kiymoq" },
    { "english": "paper", "uzbek": "qog‘oz" },
    { "english": "special", "uzbek": "maxsus" },
    { "english": "space", "uzbek": "bo‘sh joy / kosmos" },
    { "english": "ground", "uzbek": "yer" },
    { "english": "form", "uzbek": "shakl" },
    { "english": "support", "uzbek": "qo‘llab-quvvatlamoq" },
    { "english": "event", "uzbek": "voqeа" },
    { "english": "official", "uzbek": "rasmiy" },
    { "english": "whose", "uzbek": "kimniki" },
    { "english": "matter", "uzbek": "masala / ahamiyat" },
    { "english": "everyone", "uzbek": "hamma" },
    { "english": "center", "uzbek": "markaz" },
    { "english": "couple", "uzbek": "juft / er-xotin" },
    { "english": "site", "uzbek": "joy / sayt" },
    { "english": "end", "uzbek": "oxir" },
    { "english": "project", "uzbek": "loyiha" },
    { "english": "hit", "uzbek": "urmoq" },
    { "english": "base", "uzbek": "asos" },
    { "english": "activity", "uzbek": "faoliyat" },
    { "english": "star", "uzbek": "yulduz" },
    { "english": "table", "uzbek": "stol" },
    { "english": "need", "uzbek": "zaruriyat / ehtiyoj" },
    { "english": "court", "uzbek": "sud" },
    { "english": "produce", "uzbek": "ishlab chiqarmoq" },
    { "english": "eat", "uzbek": "yemoq" },
    { "english": "american", "uzbek": "amerikalik" },
    { "english": "teach", "uzbek": "o‘qitmoq" },
    { "english": "oil", "uzbek": "neft / moy" },
    { "english": "half", "uzbek": "yarmi" },
    { "english": "situation", "uzbek": "vaziyat" },
    { "english": "easy", "uzbek": "oson" },
    { "english": "cost", "uzbek": "narx / xarajat" },
    { "english": "industry", "uzbek": "sanoat" },
    { "english": "figure", "uzbek": "raqam / qiyofa" },
    { "english": "street", "uzbek": "ko‘cha" },
    { "english": "image", "uzbek": "tasvir" },
    { "english": "phone", "uzbek": "telefon" },
    { "english": "either", "uzbek": "ham / yoki" },
    { "english": "data", "uzbek": "ma’lumotlar" },
    { "english": "cover", "uzbek": "yopmoq / qoplamoq" },
    { "english": "quite", "uzbek": "juda" },
    { "english": "picture", "uzbek": "rasm" },
    { "english": "clear", "uzbek": "aniq / toza" },
    { "english": "practice", "uzbek": "amaliyot" },
    { "english": "piece", "uzbek": "bo‘lak" },
    { "english": "land", "uzbek": "yer / qo‘nmoq" },
    { "english": "recent", "uzbek": "so‘nggi" },
    { "english": "describe", "uzbek": "tasvirlamoq" },
    { "english": "product", "uzbek": "mahsulot" },
    { "english": "doctor", "uzbek": "shifokor" },
    { "english": "wall", "uzbek": "devor" },
    { "english": "patient", "uzbek": "bemor / sabrli" },
    { "english": "worker", "uzbek": "ishchi" },
    { "english": "news", "uzbek": "yangilik" },
    { "english": "test", "uzbek": "imtihon / test" },
    { "english": "movie", "uzbek": "kino" },
    { "english": "certain", "uzbek": "aniq / ma’lum" },
    { "english": "north", "uzbek": "shimol" },
    { "english": "personal", "uzbek": "shaxsiy" },
    { "english": "simply", "uzbek": "oddiygina" },
    { "english": "third", "uzbek": "uchinchi" },
    { "english": "technology", "uzbek": "texnologiya" },
    { "english": "catch", "uzbek": "ushlamoq" },
    { "english": "step", "uzbek": "qadam" },
    { "english": "baby", "uzbek": "chaqaloq" },
    { "english": "computer", "uzbek": "kompyuter" },
    { "english": "type", "uzbek": "tur / yozmoq" },
    { "english": "attention", "uzbek": "e’tibor" },
    { "english": "draw", "uzbek": "chizmoq" },
    { "english": "film", "uzbek": "film" },
    { "english": "republican", "uzbek": "respublikachi" },
    { "english": "tree", "uzbek": "daraxt" },
    { "english": "source", "uzbek": "manba" },
    { "english": "red", "uzbek": "qizil" },
    { "english": "nearly", "uzbek": "deyarli" },
    { "english": "organization", "uzbek": "tashkilot" },
    { "english": "choose", "uzbek": "tanlamoq" },
    { "english": "cause", "uzbek": "sabab bo‘lmoq" },
    { "english": "hair", "uzbek": "soch" },
    { "english": "look", "uzbek": "qaramoq" },
    { "english": "point", "uzbek": "nuqta / fikr" },
    { "english": "century", "uzbek": "asr" },
    { "english": "evidence", "uzbek": "dalil" },
    { "english": "window", "uzbek": "deraza" },
    { "english": "difficult", "uzbek": "qiyin" },
    { "english": "listen", "uzbek": "tinglamoq" },
    { "english": "soon", "uzbek": "tez orada" },
    { "english": "culture", "uzbek": "madaniyat" },
    { "english": "billion", "uzbek": "milliard" },
    { "english": "chance", "uzbek": "imkoniyat" },
    { "english": "brother", "uzbek": "aka / uka" },
    { "english": "energy", "uzbek": "energiya" },
    { "english": "period", "uzbek": "davr" },
    { "english": "course", "uzbek": "kurs / albatta" },
    { "english": "summer", "uzbek": "yoz fasli" },
    { "english": "less", "uzbek": "kamroq" },
    { "english": "realize", "uzbek": "anglamoq" },
    { "english": "hundred", "uzbek": "yuz" },
    { "english": "available", "uzbek": "mavjud" },
    { "english": "plant", "uzbek": "o‘simlik / zavod" },
    { "english": "likely", "uzbek": "ehtimol" },
    { "english": "opportunity", "uzbek": "imkoniyat" },
    { "english": "term", "uzbek": "muddat / atama" },
    { "english": "short", "uzbek": "qisqa" },
    { "english": "letter", "uzbek": "xat / harf" },
    { "english": "condition", "uzbek": "shart / holat" },
    { "english": "choice", "uzbek": "tanlov" },
    { "english": "place", "uzbek": "joy" },
    { "english": "single", "uzbek": "yakka / bitta" },
    { "english": "rule", "uzbek": "qoidа" },
    { "english": "daughter", "uzbek": "qiz farzand" },
    { "english": "administration", "uzbek": "ma’muriyat" },
    { "english": "south", "uzbek": "janub" },
    { "english": "husband", "uzbek": "er" },
    { "english": "congress", "uzbek": "kongress" }
]
