const simples = [
    { "english": "forward", "uzbek": "oldinga" },
    { "english": "campaign", "uzbek": "kampaniya" },
    { "english": "farm", "uzbek": "ferma" },
    { "english": "training", "uzbek": "trening / mashq" },
    { "english": "physical", "uzbek": "jismoniy" },
    { "english": "whatever", "uzbek": "nima bo‘lsa ham" },
    { "english": "analysis", "uzbek": "tahlil" },
    { "english": "seek", "uzbek": "izlamoq" },
    { "english": "produce", "uzbek": "ishlab chiqarmoq" },
    { "english": "street", "uzbek": "ko‘cha" },
    { "english": "ready", "uzbek": "tayyor" },
    { "english": "rest", "uzbek": "dam olish / qolgan qismi" },
    { "english": "security", "uzbek": "xavfsizlik" },
    { "english": "benefit", "uzbek": "foyda" },
    { "english": "name", "uzbek": "ism / nom" },
    { "english": "author", "uzbek": "muallif" },
    { "english": "fill", "uzbek": "to‘ldirmoq" },
    { "english": "financial", "uzbek": "moliyaviy" },
    { "english": "finish", "uzbek": "tugatmoq" },
    { "english": "increase", "uzbek": "oshirmoq" },
    { "english": "station", "uzbek": "stansiya" },
    { "english": "blue", "uzbek": "ko‘k" },
    { "english": "state", "uzbek": "davlat / holat" },
    { "english": "strategy", "uzbek": "strategiya" },
    { "english": "little", "uzbek": "kichkina / oz" },
    { "english": "clearly", "uzbek": "aniq ravishda" },
    { "english": "discuss", "uzbek": "muhokama qilmoq" },
    { "english": "indeed", "uzbek": "haqiqatan ham" },
    { "english": "force", "uzbek": "majbur qilmoq / kuch" },
    { "english": "truth", "uzbek": "haqiqat" },
    { "english": "song", "uzbek": "qo‘shiq" },
    { "english": "example", "uzbek": "misol" },
    { "english": "environment", "uzbek": "muhit" },
    { "english": "technology", "uzbek": "texnologiya" },
    { "english": "suddenly", "uzbek": "to‘satdan" },
    { "english": "series", "uzbek": "seriya / ketma-ketlik" },
    { "english": "exactly", "uzbek": "aniq" },
    { "english": "opinion", "uzbek": "fikr" },
    { "english": "choose", "uzbek": "tanlamoq" },
    { "english": "success", "uzbek": "muvaffaqiyat" },
    { "english": "option", "uzbek": "variant" },
    { "english": "president", "uzbek": "prezident" },
    { "english": "meeting", "uzbek": "uchrashuv" },
    { "english": "determine", "uzbek": "aniqlamoq" },
    { "english": "future", "uzbek": "kelajak" },
    { "english": "direction", "uzbek": "yo‘nalish" },
    { "english": "increase", "uzbek": "ko‘paymoq" },
    { "english": "foreign", "uzbek": "chet el" },
    { "english": "artist", "uzbek": "san’atkor" },
    { "english": "hospital", "uzbek": "kasalxona" },
    { "english": "overall", "uzbek": "umuman olganda" },
    { "english": "advertise", "uzbek": "reklama qilmoq" },
    { "english": "civil", "uzbek": "fuqarolik" },
    { "english": "original", "uzbek": "asl" },
    { "english": "image", "uzbek": "tasvir" },
    { "english": "injury", "uzbek": "jarohat" },
    { "english": "claim", "uzbek": "da’vo qilmoq" },
    { "english": "region", "uzbek": "mintaqa" },
    { "english": "television", "uzbek": "televizor" },
    { "english": "management", "uzbek": "boshqaruv" },
    { "english": "relation", "uzbek": "aloqa / munosabat" },
    { "english": "impact", "uzbek": "ta’sir" },
    { "english": "organization", "uzbek": "tashkilot" },
    { "english": "respond", "uzbek": "javob bermoq" },
    { "english": "push", "uzbek": "itarmoq" },
    { "english": "nature", "uzbek": "tabiat" },
    { "english": "color", "uzbek": "rang" },
    { "english": "recently", "uzbek": "yaqinda" },
    { "english": "store", "uzbek": "do‘kon" },
    { "english": "reduce", "uzbek": "kamaytirmoq" },
    { "english": "sound", "uzbek": "ovoz" },
    { "english": "note", "uzbek": "eslatma / qayd" },
    { "english": "fine", "uzbek": "jarima / yaxshi" },
    { "english": "near", "uzbek": "yaqin" },
    { "english": "movement", "uzbek": "harakat" },
    { "english": "page", "uzbek": "sahifa" },
    { "english": "enter", "uzbek": "kirib bormoq" },
    { "english": "share", "uzbek": "bo‘lishmoq" },
    { "english": "common", "uzbek": "umumiy" },
    { "english": "poor", "uzbek": "kambag‘al" },
    { "english": "natural", "uzbek": "tabiiy" },
    { "english": "race", "uzbek": "poyga / irq" },
    { "english": "concern", "uzbek": "tashvish" },
    { "english": "series", "uzbek": "seriya" },
    { "english": "significant", "uzbek": "muhim" },
    { "english": "similar", "uzbek": "o‘xshash" },
    { "english": "hot", "uzbek": "issiq" },
    { "english": "language", "uzbek": "til" },
    { "english": "usually", "uzbek": "odatda" },
    { "english": "response", "uzbek": "javob" },
    { "english": "dead", "uzbek": "o‘lik" },
    { "english": "rise", "uzbek": "ko‘tarilmoq" },
    { "english": "animal", "uzbek": "hayvon" },
    { "english": "factor", "uzbek": "omil" },
    { "english": "decade", "uzbek": "o‘n yillik" },
    { "english": "article", "uzbek": "maqola" },
    { "english": "shoot", "uzbek": "otmoq" },
    { "english": "east", "uzbek": "sharq" },
    { "english": "save", "uzbek": "saqlamoq" },
    { "english": "seven", "uzbek": "yetti" },
    { "english": "artist", "uzbek": "rassom / san’atkor" },
    { "english": "scene", "uzbek": "sahna" },
    { "english": "stock", "uzbek": "zaxira / aksiya" },
    { "english": "career", "uzbek": "karera" },
    { "english": "eight", "uzbek": "sakkiz" },
    { "english": "west", "uzbek": "g‘arb" },
    { "english": "beyond", "uzbek": "narida" },
    { "english": "teacher", "uzbek": "o‘qituvchi" },
    { "english": "institution", "uzbek": "muassasa" },
    { "english": "arrive", "uzbek": "yetib kelmoq" },
    { "english": "film", "uzbek": "kino" },
    { "english": "professional", "uzbek": "professional" },
    { "english": "condition", "uzbek": "shart / holat" },
    { "english": "conference", "uzbek": "konferensiya" },
    { "english": "unit", "uzbek": "bo‘linma / birlik" },
    { "english": "style", "uzbek": "uslub" },
    { "english": "adult", "uzbek": "kattalar" },
    { "english": "worry", "uzbek": "xavotirlanmoq" },
    { "english": "range", "uzbek": "oraliq / diapazon" },
    { "english": "mention", "uzbek": "eslatmoq" },
    { "english": "rather", "uzbek": "aksincha / afzal" },
    { "english": "far", "uzbek": "uzoqqa" },
    { "english": "deep", "uzbek": "chuqur" },
    { "english": "front", "uzbek": "old" },
    { "english": "edge", "uzbek": "chegara / qirra" },
    { "english": "individual", "uzbek": "individ / shaxs" },
    { "english": "specific", "uzbek": "aniq" },
    { "english": "writer", "uzbek": "yozuvchi" },
    { "english": "trouble", "uzbek": "muammo" },
    { "english": "necessary", "uzbek": "zarur" },
    { "english": "throughout", "uzbek": "butun davomida" },
    { "english": "challenge", "uzbek": "qiyinchilik" },
    { "english": "fear", "uzbek": "qo‘rquv" },
    { "english": "shoulder", "uzbek": "yelkа" },
    { "english": "institution", "uzbek": "tashkilot" },
    { "english": "middle", "uzbek": "o‘rtа" },
    { "english": "sea", "uzbek": "dengiz" },
    { "english": "dream", "uzbek": "tush / orzu" },
    { "english": "bar", "uzbek": "bar / panjara" },
    { "english": "beautiful", "uzbek": "chiroyli" },
    { "english": "property", "uzbek": "mulk" },
    { "english": "instead", "uzbek": "o‘rniga" },
    { "english": "improve", "uzbek": "yaxshilamoq" },
    { "english": "stuff", "uzbek": "narsa" },
    { "english": "detail", "uzbek": "batafsil ma’lumot" },
    { "english": "method", "uzbek": "usul" },
    { "english": "somebody", "uzbek": "kimdir" },
    { "english": "magazine", "uzbek": "jurnal" },
    { "english": "hotel", "uzbek": "mehmonxona" },
    { "english": "soldier", "uzbek": "askar" },
    { "english": "reflect", "uzbek": "aks ettirmoq" },
    { "english": "heavy", "uzbek": "og‘ir" },
    { "english": "sexual", "uzbek": "jinsiy" },
    { "english": "bag", "uzbek": "sumka" },
    { "english": "marriage", "uzbek": "nikoh" },
    { "english": "married", "uzbek": "turmush qurgan" },
    { "english": "civilian", "uzbek": "oddiy fuqaro" },
    { "english": "plastic", "uzbek": "plastik" },
    { "english": "kitchen", "uzbek": "oshxona" },
    { "english": "speech", "uzbek": "nutq" },
    { "english": "patient", "uzbek": "bemor / sabrli" },
    { "english": "mouth", "uzbek": "og‘iz" },
    { "english": "nor", "uzbek": "ham emas" },
    { "english": "victim", "uzbek": "jabrlanuvchi" },
    { "english": "newspaper", "uzbek": "gazeta" },
    { "english": "thousand", "uzbek": "ming" },
    { "english": "threat", "uzbek": "tahdid" },
    { "english": "responsibility", "uzbek": "mas’uliyat" },
    { "english": "smile", "uzbek": "tabassum" },
    { "english": "attorney", "uzbek": "advokat" },
    { "english": "score", "uzbek": "hisob / ball" },
    { "english": "account", "uzbek": "hisob" },
    { "english": "interesting", "uzbek": "qiziqarli" },
    { "english": "breakfast", "uzbek": "nonushta" },
    { "english": "article", "uzbek": "maqola / moddа" },
    { "english": "career", "uzbek": "kasbiy yo‘l" },
    { "english": "attack", "uzbek": "hujum qilmoq" },
    { "english": "capital", "uzbek": "poytaxt / kapital" },
    { "english": "conference", "uzbek": "anjuman" },
    { "english": "hell", "uzbek": "do‘zax" },
    { "english": "proposal", "uzbek": "taklif" },
    { "english": "client", "uzbek": "mijoz" },
    { "english": "positive", "uzbek": "ijobiy" },
    { "english": "negative", "uzbek": "salbiy" },
    { "english": "file", "uzbek": "fayl / papka" },
    { "english": "advice", "uzbek": "maslahat" },
    { "english": "western", "uzbek": "g‘arbiy" },
    { "english": "sport", "uzbek": "sport" },
    { "english": "perform", "uzbek": "ijro etmoq" },
    { "english": "quickly", "uzbek": "tezda" },
    { "english": "wind", "uzbek": "shamol" },
    { "english": "pound", "uzbek": "funt / urmoq" },
    { "english": "basis", "uzbek": "asos" },
    { "english": "guest", "uzbek": "mehmon" },
    { "english": "sample", "uzbek": "namuna" },
    { "english": "publication", "uzbek": "nashr" },
    { "english": "story", "uzbek": "hikoya" },
    { "english": "conference", "uzbek": "konferensiya" }
]
