const simples = [
  { english: "and", uzbek: "va" },
  { english: "because", uzbek: "chunki" },
  { english: "so", uzbek: "shuning uchun" },
  { english: "or", uzbek: "yoki" },
  { english: "if", uzbek: "agar" },
  { english: "but", uzbek: "lekin" },
  { english: "after", uzbek: "keyin" },
  { english: "as", uzbek: "dek" },
  { english: "since", uzbek: "dan beri" },
  { english: "until", uzbek: "gacha" },
  { english: "while", uzbek: "paytda" },
  { english: "for", uzbek: "uchun" },
  { english: "unless", uzbek: "agar" },
  { english: "as well as", uzbek: "shuningdek" },
  { english: "either...or", uzbek: "yoki...yo" },
  { english: "as long as", uzbek: "qadar" },
  { english: "as if", uzbek: "xuddi" },
  { english: "as...as", uzbek: "dek kabi" },
  { english: "that", uzbek: "ga qaraganda" },
  { english: "so that", uzbek: "uchun" },
  { english: "what", uzbek: "nima" },
  { english: "when", uzbek: "qachon" },
  { english: "who", uzbek: "kim" },
  { english: "where", uzbek: "qayer" },
  { english: "which", uzbek: "qaysi" },
  { english: "how", uzbek: "qanday" },
  { english: "how many", uzbek: "nechta" },
  { english: "how much", uzbek: "qancha" },
  { english: "should", uzbek: "kerak" },
  { english: "must", uzbek: "kerak" },
  { english: "have to", uzbek: "kerak" },
  { english: "can", uzbek: "qila olmoq" },
  { english: "could", uzbek: "qila olmoq" },
  { english: "may", uzbek: "mumkin" },
  { english: "might", uzbek: "mumkin" },
  { english: "ought to", uzbek: "kerak" },
  { english: "love", uzbek: "sevmoq" },
  { english: "believe", uzbek: "ishonmoq" },
  { english: "be", uzbek: "bo'lmoq" },
  { english: "know", uzbek: "bilmoq" },
  { english: "possess", uzbek: "egalik qilmoq" },
  { english: "forget", uzbek: "unutmoq" },
  { english: "remember", uzbek: "eslamoq" },
  { english: "understand", uzbek: "tushunmoq" },
  { english: "notice", uzbek: "payqamoq" },
  { english: "feel", uzbek: "his qilmoq" },
  { english: "hear", uzbek: "eshitmoq" },
  { english: "see", uzbek: "ko'rmoq" },
  { english: "wish", uzbek: "xohlamoq" },
  { english: "want", uzbek: "istamoq" },
  // { english: "like", uzbek: "yoqtirmoq" },
  // { english: "hate", uzbek: "nafratlanmoq" },
  // { english: "seem", uzbek: "tuyilmoq" },
  // { english: "about", uzbek: "haqida" },
  // { english: "about", uzbek: "taxminan" },
  // { english: "about", uzbek: "atrofida" },
  // { english: "above", uzbek: "ustida" },
  // { english: "across", uzbek: "ko'ndalangiga" },
  // { english: "after", uzbek: "keyin" },
  // { english: "against", uzbek: "qarshi" },
  // { english: "along", uzbek: "bo'ylab" },
  // { english: "among", uzbek: "orasida" },
  // { english: "at", uzbek: "yonida, da" },
  // { english: "before", uzbek: "avval" },
  // { english: "behind", uzbek: "orqasida" },
  // { english: "below", uzbek: "ostida" },
  // { english: "beside", uzbek: "yonida" },
  // { english: "besides", uzbek: "dan tashqari" },
  // { english: "by", uzbek: "tomonidan, vositasida" },
  // { english: "between", uzbek: "o'rtasida" },
  // { english: "beyond", uzbek: "orqasida" },
  // { english: "down", uzbek: "pastga" },
  // { english: "during", uzbek: "davomida" },
  // { english: "except", uzbek: "dan tashqari" },
  // { english: "for", uzbek: "uchun" },
  // { english: "from", uzbek: "dan" },
  // { english: "in", uzbek: "da, ichida" },
  // { english: "inside", uzbek: "ichiga" },
  // { english: "with", uzbek: "bilan" },
  // { english: "without", uzbek: "...siz" },
  // { english: "within", uzbek: "ichida" },
  // { english: "up", uzbek: "yuqoriga" },
  // { english: "under", uzbek: "tagida" },
  // { english: "towards", uzbek: "ga qarab" },
  // { english: "to", uzbek: "ga" },
  // { english: "till", uzbek: "gacha" },
  // { english: "until", uzbek: "gacha" },
  // { english: "round", uzbek: "atrofida" },
  // { english: "around", uzbek: "atrofida" },
  // { english: "past", uzbek: "yonidan" },
  // { english: "over", uzbek: "ustidan" },
  // { english: "out", uzbek: "tashqari" },
  // { english: "outside", uzbek: "tashqarida" },
  // { english: "on", uzbek: "da, ustida" },
  // { english: "of", uzbek: "ning" },
  // { english: "off", uzbek: "ustidan" },
  // { english: "into", uzbek: "ichiga" },
  // { english: "since", uzbek: "dan buyon" },
  // { english: "hold on", uzbek: "kutmoq" },
  // { english: "carry on", uzbek: "davom etmoq" },
  // { english: "go / walk / drive on", uzbek: "yo'lda davom etmoq" },
  // { english: "fall off", uzbek: "tushib ketmoq" },
  // { english: "take off", uzbek: "ko'tarilmoq" },
  // { english: "stand up", uzbek: "turmoq" },
  // { english: "go up", uzbek: "balandlamoq" },
  // { english: "look up", uzbek: "qaramoq" },
  // { english: "wake up", uzbek: "uyg'onmoq" },
  // { english: "get up", uzbek: "o'rindan turmoq" },
  // { english: "grow up", uzbek: "ulg'aymoq" },
  // { english: "speak up", uzbek: "balandroq gapirmoq" },
  // { english: "wash up", uzbek: "yuvmoq" },
  // { english: "hurry up", uzbek: "shoshilmoq" },
  // { english: "give up", uzbek: "harakatdan to'xtamoq" },
  // { english: "sit down", uzbek: "o'tirmoq" },
  // { english: "lie down", uzbek: "uyquga yotmoq" },
  // { english: "fall down", uzbek: "qulamoq" },
  // { english: "slow down", uzbek: "sekinlamoq" },
  // { english: "break down", uzbek: "buzilmoq" },
  // { english: "run away (or off)", uzbek: "yugurib ketmoq" },
  // { english: "come back", uzbek: "qaytib kelmoq" },
  // { english: "look round", uzbek: "burilib qaramoq" },
  // { english: "fall over", uzbek: "yiqilmoq" },
  // { english: "climb over", uzbek: "oshib o'tmoq" },
  // { english: "chance upon", uzbek: "tasodifan ko’rib qolmoq" },
  // { english: "change around", uzbek: "atrofni o’zgartirmoq" },
  // {
  //   english: "change into",
  //   uzbek: "holat va vaziyatni o’zgartirmoq; kiyimini almashtirmoq",
  // },
  // { english: "change out of", uzbek: "kiyimini almashtirmoq" },
  // { english: "clock up", uzbek: "ma’lum bir miqdorga yetishmoq" },
  // { english: "club together", uzbek: "pul yig’moq (jamoa b-n)" },
  // { english: "close up", uzbek: "yopib tashlamoq" },
  // { english: "close down", uzbek: "ishlashdan to'xtamoq (kompaniya uchun)" },
  // { english: "come off", uzbek: "muvaffaqiyatli chiqmoq" },
  // { english: "come on", uzbek: "rivojlanmoq" },
  // { english: "come up with", uzbek: "biror narsa haqida o’ylamoq" },
  // { english: "cut off", uzbek: "ta’minotni to'xtatmoq" },
  // { english: "come on", uzbek: "namoish qilina boshlamoq" },
  // { english: "come out", uzbek: "chop etmoq" },
  // { english: "come forward", uzbek: "yordam yoki ma’lumot taklif etmoq" },
  // { english: "come down with", uzbek: "og’ir kasallikka chalinmoq" },
  // { english: "come round/to", uzbek: "xushiga kelmoq" },
  // { english: "come (a) round (to)", uzbek: "o’ziga kelmoq" },
  // { english: "come across", uzbek: "tasodifan duch kelmoq" },
  // { english: "come by", uzbek: "olishi qiyin bo’lgan narsani olmoq" },
  // { english: "go in", uzbek: "ichkariga kirmoq" },
  // { english: "walk in", uzbek: "yurib kirmoq" },
  // { english: "look out", uzbek: "tashqariga qaramoq / ehtiyot bo'l" },
  // { english: "get out", uzbek: "transportdan tushmoq" },
  // { english: "get on", uzbek: "transportga chiqmoq" },
  // { english: "come on", uzbek: "bo'laqol" },
  // { english: "hold on", uzbek: "kutmoq" },
  // { english: "carry on", uzbek: "davom etmoq" },
  // { english: "go / walk / drive on", uzbek: "yo'lda davom etmoq" },
  // { english: "fall off", uzbek: "tushib ketmoq" },
  // { english: "take off", uzbek: "ko'tarilmoq" },
  // { english: "stand up", uzbek: "turmoq" },
  // { english: "go up", uzbek: "balandlamoq" },
  // { english: "look up", uzbek: "qaramoq" },
  // { english: "wake up", uzbek: "uyg'onmoq" },
  // { english: "get up", uzbek: "o'rindan turmoq" },
  // { english: "grow up", uzbek: "ulg'aymoq" },
  // { english: "speak up", uzbek: "balandroq gapirmoq" },
  // { english: "wash up", uzbek: "yuvmoq" },
  // { english: "hurry up", uzbek: "shoshilmoq" },
  // { english: "give up", uzbek: "harakatdan to'xtamoq" },
  // { english: "sit down", uzbek: "o'tirmoq" },
  // { english: "lie down", uzbek: "uyquga yotmoq" },
  // { english: "fall down", uzbek: "qulamoq" },
  // { english: "slow down", uzbek: "sekinlamoq" },
  // { english: "break down", uzbek: "buzilmoq" },
  // { english: "run away (or off)", uzbek: "yugurib ketmoq" },
  // { english: "come back", uzbek: "qaytib kelmoq" },
  // { english: "look round", uzbek: "burilib qaramoq" },
  // { english: "fall over", uzbek: "yiqilmoq" },
  // { english: "climb over", uzbek: "oshib o'tmoq" },
  // { english: "fed up with", uzbek: "joniga tegmoq" },
  // { english: "famous for", uzbek: "mashhur" },
  // { english: "frightened by", uzbek: "qo'rqmoq" },
  // { english: "envious of", uzbek: "ichi qoralik qilmoq" },
  // { english: "exhausted from", uzbek: "charchagan, holdan toygan" },
  // { english: "dressed in", uzbek: "kiyinib olgan" },
  // { english: "disappointed by", uzbek: "dan norozi bo‘lmoq" },
  // { english: "confused by", uzbek: "yanglishmoq" },
  // { english: "capable of", uzbek: "ga qobiliyatli bo‘lmoq" },
  // { english: "bored by", uzbek: "zerikkan bo‘lmoq" },
  // { english: "angry with", uzbek: "achchiqlanmoq" },
  // { english: "after all", uzbek: "ga qaramasdan" },
  // { english: "all along", uzbek: "har doim" },
  // { english: "all of a sudden", uzbek: "toshatdan" },
  // { english: "all the same", uzbek: "bir xil" },
  // { english: "as a rule", uzbek: "odatda" },
  // { english: "as far as I am concerned", uzbek: "mening fikrimcha" },
  // { english: "as for me", uzbek: "men o‘ylashimcha" },
  // { english: "be about to", uzbek: "tayyor bo‘lmoq" },
  // {
  //   english: "be back on one's feet",
  //   uzbek: "yana sog‘lom yoki moliyaviy ahvolni tiklamoq",
  // },
  // {
  //   english: "be beside oneself",
  //   uzbek: "juda xavotirlangan yoki achchiqlangan",
  // },
  // { english: "be in the red", uzbek: "qarzga botmoq" },
  // { english: "come across", uzbek: "toshatdan ko‘rib qolmoq" },
  // { english: "catch one's eye", uzbek: "e’tiborini tortmoq" },
  // { english: "have a good time", uzbek: "yaxshi vaqt o'tkazmoq" },
  // { english: "have a rest", uzbek: "dam olmoq" },
  // { english: "have a break", uzbek: "tanaffus qilmoq" },
  // { english: "have a cold", uzbek: "shamollamoq" },
  // { english: "have 3 meals a day", uzbek: "kuniga 3 mahal ovqatlanmoq" },
  // { english: "have a headache", uzbek: "boshi og'rimoq" },
  // { english: "have a toothache", uzbek: "tishi og'rimoq" },
  // { english: "have a backache", uzbek: "beli og'rimoq" },
  // { english: "have a stomachache", uzbek: "oshqozoni og'rimoq" },
  // { english: "have a sore throat", uzbek: "tomogi og'rimoq" },
  // { english: "have a flu", uzbek: "gripp bo'lmoq" },
  // { english: "have a cough", uzbek: "yotalmoq" },
  // { english: "have a sneeze", uzbek: "aksirmoq" },
  // { english: "have one's English", uzbek: "Ingliz tili bilan shug'ullanmoq" },
  // { english: "have a smoke", uzbek: "chekmoq" },
  // { english: "have a tea", uzbek: "choy ichmoq" },
  // { english: "have a dictation", uzbek: "diktant yozmoq" },

  // { english: "carry on", uzbek: "davom ettirmoq" },
  // { english: "get round to", uzbek: "(uzoq o'ylangan rejani) boshlamoq" },
  // {
  //   english: "get up to",
  //   uzbek: "1) bajarmoq; 2) qilmaslik kerak bo'lgan ishni qilmoq",
  // },
  // { english: "go in for", uzbek: "1) musobatga kirmoq; 2) yoqtirmoq" },
  // { english: "go off", uzbek: "yomon ko'rib qolmoq" },
  // { english: "join in", uzbek: "a'zo bo'lmoq" },
  // {
  //   english: "knock out",
  //   uzbek: "1) o'yindan chiqarib yubormoq; 2) xushidan ketkizmoq",
  // },
  // { english: "look out", uzbek: "ehtiyot bo'lmoq" },
  // { english: "pull out", uzbek: "to'xtatmoq, voz kechmoq" },
  // { english: "put off", uzbek: "kechiktirmoq" },
  // { english: "put up with", uzbek: "chidamoq, bardosh bermoq" },
  // { english: "take to", uzbek: "odat sifatida boshlamoq" },
  // {
  //   english: "take up",
  //   uzbek: "1) (hobby, sport) boshlamoq; 2) vaqtni olmoq",
  // },
  // { english: "great", uzbek: "zo'r" },
  // { english: "fantastic", uzbek: "ajoyib" },
  // { english: "wonderful", uzbek: "a'lo" },
  // { english: "splendid", uzbek: "a'lo darajada" },
  // { english: "excellent", uzbek: "mukammal" },
  // { english: "amazing", uzbek: "hayratlanarli" },
  // { english: "incredible", uzbek: "ishonib bo'lmaydigan" },
  // { english: "awesome", uzbek: "ajoyib" },
  // { english: "the best", uzbek: "eng yaxshi" },
  // { english: "impressive", uzbek: "ta'sirli" },
  // { english: "breathtaking", uzbek: "nafasni kesadigan" },
  // { english: "marvellous", uzbek: "ajoyib" },
  // { english: "unbelievable", uzbek: "ishonib bo'lmaydigan" },
  // { english: "remarkable", uzbek: "diqqatga sazovor" },
  // { english: "astonishing", uzbek: "hayratlanarli" },
  // { english: "extraordinary", uzbek: "g'ayrioddiy" },
  // { english: "fascinating", uzbek: "jalb qiluvchi" },
  // { english: "mind blowing", uzbek: "aqlni hayratga soladigan" },
  // { english: "unimaginable", uzbek: "tasavvurga sig'maydigan" },
  // { english: "magnificent", uzbek: "ajoyib" },
  // { english: "tremendous", uzbek: "katta, ajoyib" },
  // { english: "channel", uzbek: "kanal" },
  // { english: "group", uzbek: "guruh" },
  // { english: "forward", uzbek: "xatni yangi adressga jo'natmoq" },
  // { english: "type", uzbek: "yozmoq" },
  // { english: "online", uzbek: "internetga ulangan" },
  // { english: "record voice", uzbek: "ovoz yozmoq" },
  // { english: "send file", uzbek: "rasm, video... yubormoq" },
  // { english: "search", uzbek: "qidirmoq (qidiruv)" },
  // { english: "last seen at...", uzbek: "...da oxiri ko'rilgan" },
  // { english: "last seen recently", uzbek: "yaqinda ko'rilgan" },
  // {
  //   english: "last seen within week (month)",
  //   uzbek: "oxiri hafta davomida ko'rilgan (oy davomida)",
  // },
  // { english: "deleted account", uzbek: "o'chirilgan akkaunt" },
  // { english: "block", uzbek: "to'smoq" },
  // { english: "join", uzbek: "qo'shilmoq" },
  // { english: "leave", uzbek: "tark etmoq" },
  // { english: "add", uzbek: "qo'shmoq" },

  // { english: "Catch me later", uzbek: "Keyinroq gaplashamiz" },
  // { english: "Clear the way!", uzbek: "Yo'lni bo'shating" },
  // {
  //   english: "Come back anytime",
  //   uzbek: "Xohlagan paytda yana tashrif buyuring",
  // },
  // { english: "Come right in", uzbek: "Kirib o'ting" },
  // {
  //   english: "Could I call you later?",
  //   uzbek: "Keyinroq qo'ng'iroq qilsam maylimi?",
  // },
  // { english: "Could I join you?", uzbek: "Sizga qo'shilsam bo'ladimi?" },
  // { english: "Don't push (me)!", uzbek: "Menga bunday gapirmang!" },
  // { english: "Enjoy your meal!", uzbek: "Yoqimli ishtaha" },
  // { english: "Guess what!", uzbek: "Nimaligini toping!" },
  // { english: "I doubt that.", uzbek: "Shubhalanayapman" },
  // { english: "I had a lovely time", uzbek: "Vaqtimni yaxshi o'tkazdim" },
  // { english: "I spoke too soon", uzbek: "O'ylamay gapirib yuboribman" },
  // { english: "Keep in touch.", uzbek: "Aloqada bo'lib turing" },
  // { english: "Leave it to me.", uzbek: "Buni menga qo'yib bering" },
  // {
  //   english: "Make it two.",
  //   uzbek: "Menga ham qo'shib oling (asosan kafelarda)",
  // },
  // { english: "No can do.", uzbek: "Buni qila olmayman" },
  // { english: "No way!", uzbek: "Hechamda!" },
  // { english: "Pull up a chair.", uzbek: "Bizga qo'shiling" },
  // { english: "Shut up!", uzbek: "Og'zingni yop" },
  // { english: "Sit down, please.", uzbek: "O'tiring marhamat" },
  // { english: "Right you are", uzbek: "Siz haqsiz" },
  // { english: "Sure", uzbek: "Turgan gap" },
  // { english: "That’s fine", uzbek: "Juda soz bo’libdi" },
  // { english: "That’s just it", uzbek: "Xuddi shunday" },
  // { english: "That’s right", uzbek: "To’g’ri" },
  // { english: "Undoubtedly", uzbek: "Shubhasiz" },
  // { english: "Very good", uzbek: "Juda yaxshi" },
  // { english: "Willingly", uzbek: "Bajonidil" },
  // { english: "With pleasure", uzbek: "Jon deb" },
  // { english: "Yes, certainly", uzbek: "Ha, albatta" },
  // { english: "Rest of my life", uzbek: "Butun umr, qolgan umr" },
  // { english: "Piss somebody", uzbek: "Jonga tegmoq, g'azablanmoq" },
  // { english: "Beg", uzbek: "Yolvormoq" },
  // { english: "Exact same", uzbek: "Huddi shunaqa, bir xil" },
  // { english: "What time is it?", uzbek: "Soat necha bo'ldi?" },
  // { english: "Give me this", uzbek: "Buni menga bering" },
  // { english: "Are you sure?", uzbek: "Aminmisiz?" },
  // { english: "Take this!", uzbek: "Oling!" },
  // { english: "It's freezing", uzbek: "Juda sovuq" },
  // { english: "It's cold", uzbek: "Sovuq" },
  // { english: "It's hot", uzbek: "Issiq" },
  // { english: "Do you like it?", uzbek: "Senga yoqadimi?" },
  // { english: "I really like it!", uzbek: "Menga yoqadi!" },
  // { english: "I'm hungry", uzbek: "Qornim och" },
  // { english: "I'm thirsty", uzbek: "Chanqadim" },
  // { english: "He is funny", uzbek: "U kulguli" },
  // { english: "In the morning", uzbek: "Ertalab" },
  // { english: "In the evening", uzbek: "Kechqurun" },
  // { english: "At night", uzbek: "Tunda" },
];
