const simples = [
  { english: "and", uzbek: "va" },
  { english: "because", uzbek: "chunki" },
  { english: "so", uzbek: "shuning uchun" },
  { english: "or", uzbek: "yoki" },
  { english: "if", uzbek: "agar" },
  { english: "but", uzbek: "lekin" },
  { english: "after", uzbek: "keyin" },
  { english: "as", uzbek: "dek" },
  { english: "since", uzbek: "dan beri" },
  { english: "until", uzbek: "gacha" },
  { english: "while", uzbek: "paytda" },
  { english: "for", uzbek: "uchun" },
  { english: "unless", uzbek: "agar" },
  { english: "as well as", uzbek: "shuningdek" },
  { english: "either...or", uzbek: "yoki...yo" },
  { english: "as long as", uzbek: "qadar" },
  { english: "as if", uzbek: "xuddi" },
  { english: "as...as", uzbek: "dek kabi" },
  { english: "that", uzbek: "ga qaraganda" },
  { english: "so that", uzbek: "uchun" },
];
