const simples = [
  // { english: "and", uzbek: "va" },
  // { english: "because", uzbek: "chunki" },
  // { english: "so", uzbek: "shuning uchun" },
  // { english: "or", uzbek: "yoki" },
  // { english: "if", uzbek: "agar" },
  // { english: "but", uzbek: "lekin" },
  // { english: "after", uzbek: "keyin" },
  // { english: "as", uzbek: "dek" },
  // { english: "since", uzbek: "dan beri" },
  // { english: "until", uzbek: "gacha" },
  // { english: "while", uzbek: "paytda" },
  // { english: "for", uzbek: "uchun" },
  // { english: "unless", uzbek: "agar" },
  // { english: "as well as", uzbek: "shuningdek" },
  // { english: "either...or", uzbek: "yoki...yo" },
  // { english: "as long as", uzbek: "qadar" },
  // { english: "as if", uzbek: "xuddi" },
  // { english: "as...as", uzbek: "dek kabi" },
  // { english: "that", uzbek: "ga qaraganda" },
  // { english: "so that", uzbek: "uchun" },
  // { english: "what", uzbek: "nima" },
  // { english: "when", uzbek: "qachon" },
  // { english: "who", uzbek: "kim" },
  // { english: "where", uzbek: "qayer" },
  // { english: "which", uzbek: "qaysi" },
  // { english: "how", uzbek: "qanday" },
  // { english: "how many", uzbek: "nechta" },
  // { english: "how much", uzbek: "qancha" },
  // { english: "should", uzbek: "kerak" },
  // { english: "must", uzbek: "kerak" },
  // { english: "have to", uzbek: "kerak" },
  // { english: "can", uzbek: "qila olmoq" },
  // { english: "could", uzbek: "qila olmoq" },
  // { english: "may", uzbek: "mumkin" },
  // { english: "might", uzbek: "mumkin" },
  // { english: "ought to", uzbek: "kerak" },
  // { english: "love", uzbek: "sevmoq" },
  // { english: "believe", uzbek: "ishonmoq" },
  // { english: "be", uzbek: "bo'lmoq" },
  // { english: "know", uzbek: "bilmoq" },
  // { english: "possess", uzbek: "egalik qilmoq" },
  // { english: "forget", uzbek: "unutmoq" },
  // { english: "remember", uzbek: "eslamoq" },
  // { english: "understand", uzbek: "tushunmoq" },
  // { english: "notice", uzbek: "payqamoq" },
  // { english: "feel", uzbek: "his qilmoq" },
  // { english: "hear", uzbek: "eshitmoq" },
  // { english: "see", uzbek: "ko'rmoq" },
  // { english: "wish", uzbek: "xohlamoq" },
  // { english: "want", uzbek: "istamoq" },
  // { english: "like", uzbek: "yoqtirmoq" },
  // { english: "hate", uzbek: "nafratlanmoq" },
  // { english: "seem", uzbek: "tuyilmoq" },
  // { english: "about", uzbek: "haqida" },
  // { english: "about", uzbek: "taxminan" },
  // { english: "about", uzbek: "atrofida" },
  // { english: "above", uzbek: "ustida" },
  // { english: "across", uzbek: "ko'ndalangiga" },
  // { english: "after", uzbek: "keyin" },
  // { english: "against", uzbek: "qarshi" },
  // { english: "along", uzbek: "bo'ylab" },
  // { english: "among", uzbek: "orasida" },
  // { english: "at", uzbek: "yonida, da" },
  // { english: "before", uzbek: "avval" },
  // { english: "behind", uzbek: "orqasida" },
  // { english: "below", uzbek: "ostida" },
  // { english: "beside", uzbek: "yonida" },
  // { english: "besides", uzbek: "dan tashqari" },
  // { english: "by", uzbek: "tomonidan, vositasida" },
  // { english: "between", uzbek: "o'rtasida" },
  // { english: "beyond", uzbek: "orqasida" },
  // { english: "down", uzbek: "pastga" },
  // { english: "during", uzbek: "davomida" },
  // { english: "except", uzbek: "dan tashqari" },
  // { english: "for", uzbek: "uchun" },
  // { english: "from", uzbek: "dan" },
  // { english: "in", uzbek: "da, ichida" },
  // { english: "inside", uzbek: "ichiga" },
  // { english: "with", uzbek: "bilan" },
  // { english: "without", uzbek: "...siz" },
  // { english: "within", uzbek: "ichida" },
  // { english: "up", uzbek: "yuqoriga" },
  // { english: "under", uzbek: "tagida" },
  // { english: "towards", uzbek: "ga qarab" },
  // { english: "to", uzbek: "ga" },
  // { english: "till", uzbek: "gacha" },
  // { english: "until", uzbek: "gacha" },
  // { english: "round", uzbek: "atrofida" },
  // { english: "around", uzbek: "atrofida" },
  // { english: "past", uzbek: "yonidan" },
  // { english: "over", uzbek: "ustidan" },
  // { english: "out", uzbek: "tashqari" },
  // { english: "outside", uzbek: "tashqarida" },
  // { english: "on", uzbek: "da, ustida" },
  // { english: "of", uzbek: "ning" },
  // { english: "off", uzbek: "ustidan" },
  // { english: "into", uzbek: "ichiga" },
  // { english: "since", uzbek: "dan buyon" },
  // { english: "take off", uzbek: "ko'tarilmoq" },

  { english: "stand up", uzbek: "turmoq" },
  { english: "go up", uzbek: "balandlamoq" },
  { english: "look up", uzbek: "qaramoq" },
  { english: "wake up", uzbek: "uyg'onmoq" },
  { english: "get up", uzbek: "o'rindan turmoq" },
  { english: "grow up", uzbek: "ulg'aymoq" },
  { english: "speak up", uzbek: "balandroq gapirmoq" },
  { english: "wash up", uzbek: "yuvmoq" },
  { english: "hurry up", uzbek: "shoshilmoq" },
  { english: "give up", uzbek: "harakatdan to'xtamoq" },
  { english: "run away (or off)", uzbek: "yugurib ketmoq" },
  { english: "come back", uzbek: "qaytib kelmoq" },
  { english: "look round", uzbek: "burilib qaramoq" },
  { english: "fall over", uzbek: "yiqilmoq" },
  { english: "get out", uzbek: "transportdan tushmoq" },
  { english: "get on", uzbek: "transportga chiqmoq" },
  { english: "come on", uzbek: "bo'laqol" },
  { english: "fed up with", uzbek: "joniga tegmoq" },
  { english: "famous for", uzbek: "mashhur" },
  { english: "envious of", uzbek: "ichi qoralik qilmoq" },

  // { english: "disappointed by", uzbek: "dan norozi bo‘lmoq" },
  // { english: "bored by", uzbek: "zerikkan bo‘lmoq" },
  // { english: "angry with", uzbek: "achchiqlanmoq" },
  // { english: "after all", uzbek: "ga qaramasdan" },
  // { english: "be about to", uzbek: "tayyor bo‘lmoq" },
  // { english: "come across", uzbek: "toshatdan ko‘rib qolmoq" },
  // { english: "have a good time", uzbek: "yaxshi vaqt o'tkazmoq" },
  // { english: "have a rest", uzbek: "dam olmoq" },
  // { english: "have a break", uzbek: "tanaffus qilmoq" },
  // { english: "have a cold", uzbek: "shamollamoq" },
  // { english: "have a meals a day", uzbek: "kuniga 3 mahal ovqatlanmoq" },
  // { english: "have a headache", uzbek: "boshi og'rimoq" },
  // { english: "have a toothache", uzbek: "tishi og'rimoq" },
  // { english: "have a backache", uzbek: "beli og'rimoq" },
  // { english: "have a stomachache", uzbek: "oshqozoni og'rimoq" },
  // { english: "have a sore throat", uzbek: "tomogi og'rimoq" },
  // { english: "have a flu", uzbek: "gripp bo'lmoq" },
  // { english: "have a cough", uzbek: "yotalmoq" },
  // { english: "have a sneeze", uzbek: "aksirmoq" },
  // { english: "have a smoke", uzbek: "chekmoq" },
  // { english: "have a tea", uzbek: "choy ichmoq" },
  // { english: "have a dictation", uzbek: "diktant yozmoq" },
  // { english: "look out", uzbek: "ehtiyot bo'lmoq" },
  // { english: "pull out", uzbek: "to'xtatmoq, voz kechmoq" },
  // { english: "great", uzbek: "zo'r" },
  // { english: "fantastic", uzbek: "ajoyib" },
  // { english: "wonderful", uzbek: "a'lo" },
  // { english: "splendid", uzbek: "a'lo darajada" },
  // { english: "excellent", uzbek: "mukammal" },
  // { english: "amazing", uzbek: "hayratlanarli" },
  // { english: "incredible", uzbek: "ishonib bo'lmaydigan" },
  // { english: "awesome", uzbek: "ajoyib" },
  // { english: "the best", uzbek: "eng yaxshi" },
  // { english: "impressive", uzbek: "ta'sirli" },
  // { english: "marvellous", uzbek: "ajoyib" },
  // { english: "remarkable", uzbek: "diqqatga sazovor" },
  // { english: "astonishing", uzbek: "hayratlanarli" },
  // { english: "extraordinary", uzbek: "g'ayrioddiy" },
  // { english: "fascinating", uzbek: "jalb qiluvchi" },
  // { english: "mind blowing", uzbek: "aqlni hayratga soladigan" },
  // { english: "unimaginable", uzbek: "tasavvurga sig'maydigan" },
  // { english: "magnificent", uzbek: "ajoyib" },
  // { english: "tremendous", uzbek: "katta, ajoyib" },
  // { english: "channel", uzbek: "kanal" },
  // { english: "group", uzbek: "guruh" },
  // { english: "forward", uzbek: "xatni yangi adressga jo'natmoq" },
  // { english: "type", uzbek: "yozmoq" },
  // { english: "online", uzbek: "internetga ulangan" },
  // { english: "record voice", uzbek: "ovoz yozmoq" },
  // { english: "send file", uzbek: "rasm, video... yubormoq" },
  // { english: "search", uzbek: "qidirmoq (qidiruv)" },
  // { english: "last seen recently", uzbek: "yaqinda ko'rilgan" },
  // {
  //   english: "last seen within week (month)",
  //   uzbek: "oxiri hafta davomida ko'rilgan (oy davomida)",
  // },
  // { english: "deleted account", uzbek: "o'chirilgan akkaunt" },
  // { english: "block", uzbek: "to'smoq" },
  // { english: "join", uzbek: "qo'shilmoq" },
  // { english: "leave", uzbek: "tark etmoq" },
  // { english: "add", uzbek: "qo'shmoq" },
  // { english: "Catch me later", uzbek: "Keyinroq gaplashamiz" },
  // {
  //   english: "Come back anytime",
  //   uzbek: "Xohlagan paytda yana tashrif buyuring",
  // },
  // { english: "Come right in", uzbek: "Kirib o'ting" },
  // {
  //   english: "Could I call you later?",
  //   uzbek: "Keyinroq qo'ng'iroq qilsam maylimi?",
  // },
  // { english: "Could I join you?", uzbek: "Sizga qo'shilsam bo'ladimi?" },
  // { english: "Enjoy your meal!", uzbek: "Yoqimli ishtaha" },
  // { english: "Guess what!", uzbek: "Nimaligini toping!" },
  // { english: "I doubt that.", uzbek: "Shubhalanayapman" },
  // { english: "I had a lovely time", uzbek: "Vaqtimni yaxshi o'tkazdim" },
  // { english: "Leave it to me.", uzbek: "Buni menga qo'yib bering" },
  // {
  //   english: "Make it two.",
  //   uzbek: "Menga ham qo'shib oling (asosan kafelarda)",
  // },
  // { english: "No can do.", uzbek: "Buni qila olmayman" },
  // { english: "No way!", uzbek: "Hechamda!" },
  // { english: "Shut up!", uzbek: "Og'zingni yop" },
  // { english: "Right you are", uzbek: "Siz haqsiz" },
  // { english: "Sure", uzbek: "Ishonch hosil qilmoq" },
  // { english: "Undoubtedly", uzbek: "Shubhasiz" },
  // { english: "Very good", uzbek: "Juda yaxshi" },
  // { english: "With pleasure", uzbek: "Jon deb" },
  // { english: "Yes, certainly", uzbek: "Ha, albatta" },
  // { english: "Rest of my life", uzbek: "Butun umr, qolgan umr" },
  // { english: "Piss somebody", uzbek: "Jonga tegmoq, g'azablanmoq" },
  // { english: "Beg", uzbek: "Yolvormoq" },
  // { english: "Exact same", uzbek: "Huddi shunaqa, bir xil" },
  // { english: "What time is it?", uzbek: "Soat necha bo'ldi?" },
  // { english: "Give me this", uzbek: "Buni menga bering" },
  // { english: "Are you sure?", uzbek: "Aminmisiz?" },
  // { english: "Take this!", uzbek: "Oling!" },
  // { english: "It's freezing", uzbek: "Juda sovuq" },
  // { english: "It's cold", uzbek: "Sovuq" },
  // { english: "It's hot", uzbek: "Issiq" },
  // { english: "Do you like it?", uzbek: "Senga yoqadimi?" },
  // { english: "I really like it!", uzbek: "Menga yoqadi!" },
  // { english: "I'm hungry", uzbek: "Qornim och" },
  // { english: "I'm thirsty", uzbek: "Chanqadim" },
  // { english: "He is funny", uzbek: "U kulguli" },
  // { english: "In the morning", uzbek: "Ertalab" },
  // { english: "In the evening", uzbek: "Kechqurun" },
  // { english: "At night", uzbek: "Tunda" },
];
