const verbs = [
  { english: "learn", uzbek: "o'rganmoq" },
  { english: "become", uzbek: "aylanib qolmoq" },
  { english: "come", uzbek: "kelmoq" },
  { english: "include", uzbek: "o'z ichiga olmoq" },
  { english: "thank", uzbek: "raxmat aytmoq" },
  { english: "provide", uzbek: "taminlamoq" },
  { english: "create", uzbek: "yaratmoq" },
  { english: "add", uzbek: "qo'shmoq" },
  { english: "understand", uzbek: "tushunmoq" },
  { english: "consider", uzbek: "xisobga olmoq" },
  { english: "choose", uzbek: "tanlamoq" },
  { english: "develop", uzbek: "rivojlanmoq" },
  { english: "remember", uzbek: "eslamoq" },
  { english: "determine", uzbek: "aniqlamoq" },
  { english: "grow", uzbek: "ulg'aymoq" },
  { english: "allow", uzbek: "ruxsat bermoq" },
  { english: "supply", uzbek: "taminlamoq" },
  { english: "bring", uzbek: "olib kelmoq" },
  { english: "improve", uzbek: "rivojlanmoq" },
  { english: "maintain", uzbek: "saqlab qolmoq" },
  // { english: "begin", uzbek: "boshlamoq" },
  // { english: "exist", uzbek: "mavjud bo'lmoq" },
  // { english: "tend", uzbek: "moyil bo'lmoq" },
  // { english: "enjoy", uzbek: "roxatlanmoq" },
  // { english: "perform", uzbek: "bajarmoq" },
  // { english: "decide", uzbek: "qaror qilmoq" },
  // { english: "identify", uzbek: "aniqlamoq" },
  // { english: "continue", uzbek: "davom etmoq" },
  // { english: "protect", uzbek: "ximoya qilmoq" },
  // { english: "require", uzbek: "talab qilmoq" },
];
