const verbs = [
  { english: "learn", uzbek: "o'rganmoq" },
  { english: "become", uzbek: "aylanib qolmoq" },
  { english: "come", uzbek: "kelmoq" },
  { english: "include", uzbek: "o'z ichiga olmoq" },
  { english: "thank", uzbek: "raxmat aytmoq" },
  { english: "provide", uzbek: "taminlamoq" },
  { english: "create", uzbek: "yaratmoq" },
  { english: "add", uzbek: "qo'shmoq" },
  { english: "understand", uzbek: "tushunmoq" },
  { english: "consider", uzbek: "xisobga olmoq" },
  { english: "choose", uzbek: "tanlamoq" },
  { english: "develop", uzbek: "rivojlanmoq" },
  { english: "remember", uzbek: "eslamoq" },
  { english: "determine", uzbek: "aniqlamoq" },
  { english: "grow", uzbek: "ulg'aymoq" },
  { english: "allow", uzbek: "ruxsat bermoq" },
  { english: "supply", uzbek: "taminlamoq" },
  { english: "bring", uzbek: "olib kelmoq" },
  { english: "improve", uzbek: "rivojlanmoq" },
  { english: "maintain", uzbek: "saqlab qolmoq" },
  { english: "begin", uzbek: "boshlamoq" },
  { english: "exist", uzbek: "mavjud bo'lmoq" },
  { english: "tend", uzbek: "moyil bo'lmoq" },
  { english: "enjoy", uzbek: "rohatlanmoq" },
  { english: "perform", uzbek: "bajarmoq" },
  { english: "decide", uzbek: "qaror qilmoq" },
  { english: "identify", uzbek: "aniqlamoq" },
  { english: "continue", uzbek: "davom etmoq" },
  { english: "protect", uzbek: "himoya qilmoq" },
  { english: "require", uzbek: "talab qilmoq" },
  { english: "occur", uzbek: "yuzaga kelmoq" },
  { english: "write", uzbek: "yozmoq" },
  { english: "approach", uzbek: "tatbiq qilmoq" },
  { english: "avoid", uzbek: "qochmoq" },
  { english: "prepare", uzbek: "tayyorlamoq" },
  { english: "build", uzbek: "qurmoq" },
  { english: "achieve", uzbek: "erishmoq" },
  { english: "believe", uzbek: "ishonmoq" },
  { english: "receive", uzbek: "qabul qilmoq" },
  { english: "seem", uzbek: "tuyilmoq" },
  { english: "discuss", uzbek: "muhokama qilmoq" },
  { english: "realize", uzbek: "anglamoq" },
  { english: "contain", uzbek: "o'z ichiga olmoq" },
  { english: "follow", uzbek: "ergashmoq" },
  { english: "refer", uzbek: "murojaat qilmoq" },
  { english: "solve", uzbek: "yechim topmoq" },
  { english: "describe", uzbek: "tasvirlamoq" },
  { english: "prefer", uzbek: "afzal ko'rmoq" },
  { english: "prevent", uzbek: "oldini olmoq" },
  { english: "discover", uzbek: "kashf qilmoq" },
  // { english: "ensure", uzbek: "taminlamoq" },
  // { english: "expect", uzbek: "kutmoq" },
  // { english: "invest", uzbek: "sarmoya kiritmoq" },
  // { english: "reduce", uzbek: "kamaytirmoq" },
  // { english: "speak", uzbek: "gapirmoq" },
  // { english: "appear", uzbek: "ko'rinmoq" },
  // { english: "explain", uzbek: "tushuntirmoq" },
  // { english: "explore", uzbek: "kashf qilmoq" },
  // { english: "involve", uzbek: "jalb qilish" },
  // { english: "lose", uzbek: "yo'qotmoq" },
  // { english: "afford", uzbek: "qurbi yetmoq" },
  // { english: "agree", uzbek: "rozi bo'lmoq" },
  // { english: "hear", uzbek: "eshitmoq" },
  // { english: "remain", uzbek: "qonmoq" },
  // { english: "represent", uzbek: "ifodalamoq" },
  // { english: "apply", uzbek: "hujjat topshirmoq" },
  // { english: "forget", uzbek: "unutmoq" },
  // { english: "recommend", uzbek: "tafsiya etmoq" },
  // { english: "rely", uzbek: "tayanmoq" },
  // { english: "vary", uzbek: "farqlamoq" },
  // { english: "generate", uzbek: "issiqlik chiqarmoq" },
  // { english: "obtain", uzbek: "olmoq" },
  // { english: "accept", uzbek: "qabul qilmoq" },
  // { english: "communicate", uzbek: "aloqa qilmoq" },
  // { english: "complain", uzbek: "shikoyat qilmoq" },
  // { english: "depend", uzbek: "bog'liq bo'lmoq" },
  // { english: "enter", uzbek: "kirmoq" },
  // { english: "happen", uzbek: "sodir bo'lmoq" },
  // { english: "indicate", uzbek: "ko'rsatmoq" },
  // { english: "suggest", uzbek: "taklif qilmoq" },
  // { english: "survive", uzbek: "omon qolmoq" },
  // { english: "appreciate", uzbek: "qadrlamoq" },
  // { english: "compare", uzbek: "taqqoslamoq" },
  // { english: "imagine", uzbek: "tasavvur qilmoq" },
  // { english: "manage", uzbek: "boshqarmoq" },
  // { english: "differ", uzbek: "farq qilmoq" },
  // { english: "encourage", uzbek: "undamoq" },
  // { english: "expand", uzbek: "kengaytirmoq" },
  // { english: "prove", uzbek: "isbotlamoq" },
  // { english: "react", uzbek: "reaksiya bermoq" },
  // { english: "recognize", uzbek: "tanib olmoq" },
  // { english: "relax", uzbek: "dam olmoq" },
  // { english: "replace", uzbek: "almashtirmoq" },
  // { english: "borrow", uzbek: "qarz olmoq" },
  // { english: "earn", uzbek: "ishlab topmoq" },
  // { english: "emphasize", uzbek: "ta'kidlash" },
  // { english: "operate", uzbek: "ishlamoq" },
  // { english: "reflect", uzbek: "aks ettirmoq" },
  // { english: "send", uzbek: "jo'natmoq" },
  // { english: "watch", uzbek: "ko'rmoq" },
  // { english: "open", uzbek: "ochmoq" },
  // { english: "engage", uzbek: "kelishmoq" },
  // { english: "examine", uzbek: "imtihon qilmoq" },
  // { english: "install", uzbek: "o'rnatmoq" },
  // { english: "participate", uzbek: "qatnashmoq" },
  // { english: "intend", uzbek: "niyat qilmoq" },
  // { english: "introduce", uzbek: "tanishmoq" },
  // { english: "relate", uzbek: "bog'lamoq" },
  // { english: "settle", uzbek: "ishontirmoq" },
  // { english: "assure", uzbek: "kafolatlamoq" },
  // { english: "attract", uzbek: "jalb qilmoq" },
  // { english: "distribute", uzbek: "tarqatmoq" },
  // { english: "overcome", uzbek: "yengmoq" },
  // { english: "owe", uzbek: "qarz bo'lmoq" },
  // { english: "succeed", uzbek: "muvaffaqiyatga erishmoq" },
  // { english: "suffer", uzbek: "aziyat chekmoq" },
  // { english: "throw", uzbek: "otmoq" },
  // { english: "acquire", uzbek: "ega bo'lmoq" },
  // { english: "adapt", uzbek: "moslashish" },
  // { english: "adjust", uzbek: "almashtirmoq" },
  // { english: "argue", uzbek: "baxslashmoq" },
  // { english: "arise", uzbek: "o'smoq" },
  // { english: "confirm", uzbek: "tastiqlamoq" },
  // { english: "encouraging", uzbek: "rag'batlantir" },
  // { english: "incorporate", uzbek: "qo'shib olmoq" },
  // { english: "justify", uzbek: "oqlamoq" },
  // { english: "organize", uzbek: "tashkil qilmoq" },
  // { english: "ought", uzbek: "kerak bo'lmoq" },
  // { english: "possess", uzbek: "egalik qilish" },
  // { english: "relieve", uzbek: "yengillatmoq" },
  // { english: "retain", uzbek: "saqlab qolmoq" },
  // { english: "shut", uzbek: "raqobat qil" },
  // { english: "calculate", uzbek: "maslaxatlashm" },
  // { english: "compete", uzbek: "yetkazib berm" },
  // { english: "consult", uzbek: "maslaxat bermoq" },
  // { english: "deliver", uzbek: "kechikmoq" },
  // { english: "extend", uzbek: "uzytirmoq" },
  // { english: "investigate", uzbek: "tekshirmoq" },
  // { english: "negotiate", uzbek: "muzokara qilm" },
  // { english: "qualify", uzbek: "saralamoq" },
  // { english: "retired", uzbek: "nafaqaga chiqmoq" },
  // { english: "weigh", uzbek: "tortmoq taroziga" },
  // { english: "arrive", uzbek: "yetib kelmoq" },
  // { english: "attach", uzbek: "biriktirmoq" },
  // { english: "behave", uzbek: "o'zini tutmoq" },
  // { english: "celebrate", uzbek: "nishonlamoq" },
  // { english: "convince", uzbek: "ishontirmoq" },
  // { english: "disagree", uzbek: "norozi bo'lmoq" },
  // { english: "establish", uzbek: "o'rnatish" },
  // { english: "ignore", uzbek: "inkor qilmoq" },
  // { english: "imply", uzbek: "nazarda tutmoq" },
  // { english: "insist", uzbek: "turib olmoq" },
  // { english: "pursue", uzbek: "taqib qilmoq" },
  // { english: "remaining", uzbek: "qolgan" },
  // { english: "specify", uzbek: "belgilamoq" },
  // { english: "warn", uzbek: "og'oxlantirmoq" },
  // { english: "accuse", uzbek: "ayblamoq" },
  // { english: "admire", uzbek: "qoyil qolmoq" },
  // { english: "admit", uzbek: "bo'yniga olmoq" },
  // { english: "adopt", uzbek: "moslashmoq" },
  // { english: "announce", uzbek: "elon qilmoq" },
  // { english: "apologize", uzbek: "uzir so'ramoq" },
  // { english: "approve", uzbek: "xursand bo'lmoq" },
  // { english: "attend", uzbek: "qatnashmoq" },
  // { english: "arise", uzbek: "o'smoq" },
  // { english: "attend", uzbek: "qatnashmoq" },
  // { english: "belong", uzbek: "tegishli bo'lmoq" },
  // { english: "commit", uzbek: "fikr bermoq" },
  // { english: "call", uzbek: "chaqirmoq" },
  // { english: "deserve", uzbek: "yo'q qilish" },
  // { english: "destroy", uzbek: "buzmoq" },
  // { english: "hesitate", uzbek: "ikkilanmoq" },
  // { english: "illustrate", uzbek: "tasvirlamoq" },
  // { english: "inform", uzbek: "xabar bermoq" },
  // { english: "manufacturing", uzbek: "-" },
  // { english: "persuade", uzbek: "taklif qilmoq" },
  // { english: "share", uzbek: "bo'lishmoq" },
  // { english: "aim", uzbek: "maqsad qilmoq" },
  // { english: "remind", uzbek: "eslamoq" },
  // { english: "eat", uzbek: "yemoq" },
  // { english: "submit", uzbek: "topshirmoq" },
  // { english: "suppose", uzbek: "" },
  // { english: "translate", uzbek: "tarjima qilmoq" },
  // { english: "be", uzbek: "bo'lmoq" },
  // { english: "have", uzbek: "bor bo'lmoq" },
  // { english: "use", uzbek: "foydalanmoq" },
  // { english: "make", uzbek: "yasamoq" },
  // { english: "look", uzbek: "qaramoq" },
  // { english: "help", uzbek: "yordam bermoq" },
  // { english: "go", uzbek: "bormoq" },
  // { english: "being", uzbek: "bo'lmoq" },
  // { english: "think", uzbek: "o'ylamoq" },
  // { english: "read", uzbek: "o'qimoq" },
  // { english: "keep", uzbek: "saqlamoq" },
  // { english: "start", uzbek: "boshlamoq" },
  // { english: "give", uzbek: "bermoq" },
  // { english: "play", uzbek: "o'ynamoq" },
  // { english: "feel", uzbek: "his qilmoq" },
  // { english: "put", uzbek: "qo'ymoq" },
  // { english: "set", uzbek: "o'rnatmoq" },
  // { english: "change", uzbek: "o'zgartirmoq" },
  // { english: "call", uzbek: "qo'ng'iroq qilmoq" },
  // { english: "move", uzbek: "siljimoq" },
  // { english: "pay", uzbek: "to'lamoq" },
  // { english: "let", uzbek: "ruxsat bermoq" },
  // { english: "increase", uzbek: "o'smoq" },
  // { english: "turn", uzbek: "burmoq" },
  // { english: "ask", uzbek: "so'ramoq" },
  // { english: "buy", uzbek: "sotib olmoq" },
  // { english: "guard", uzbek: "qo'riqlamoq" },
  // { english: "hold", uzbek: "ushlamoq" },
  // { english: "offer", uzbek: "taklif qilmoq" },
  // { english: "travel", uzbek: "sayohat qilmoq" },
  // { english: "cook", uzbek: "pishirmoq" },
  // { english: "dance", uzbek: "raqsga tushmoq" },
  // { english: "excuse", uzbek: "kechirmoq" },
  // { english: "live", uzbek: "yashamoq" },
  // { english: "purchase", uzbek: "maqsad qilmoq" },
  // { english: "drink", uzbek: "ichmoq" },
  // { english: "mean", uzbek: "ma'nosini anglatmoq" },
  // { english: "fall", uzbek: "yiqilmoq" },
  // { english: "produce", uzbek: "ishlab chiqmoq" },
  // { english: "search", uzbek: "qidirmoq" },
  // { english: "spend", uzbek: "sarflamoq" },
  // { english: "talk", uzbek: "suhbatlashmoq" },
  // { english: "upset", uzbek: "g'azablanmoq" },
  // { english: "tell", uzbek: "aytmoq" },
  // { english: "cost", uzbek: "narxlamoq" },
  // { english: "drive", uzbek: "haydamoq" },
  // { english: "support", uzbek: "qo'llamoq" },
  // { english: "move", uzbek: "siljimoq" },
  // { english: "return", uzbek: "qaytmoq" },
  // { english: "run", uzbek: "yugurmoq" },
  // { english: "appropriate", uzbek: "moslashmoq" },
  // { english: "serve", uzbek: "xizmat qilmoq" },
  // { english: "watch", uzbek: "ko'rmoq" },
  // { english: "charge", uzbek: "zaryadlamoq" },
  // { english: "break", uzbek: "sindirmoq" },
  // { english: "stay", uzbek: "qolmoq" },
  // { english: "visit", uzbek: "tashrif buyurmoq" },
  // { english: "affect", uzbek: "ta'sir qilmoq" },
  // { english: "cover", uzbek: "qoplamoq" },
  // { english: "report", uzbek: "xabar bermoq" },
  // { english: "rise", uzbek: "ko'tarilmoq" },
  // { english: "walk", uzbek: "yurmoq" },
  // { english: "pick", uzbek: "yermoq" },
  // { english: "lift", uzbek: "ko'tarmoq" },
  // { english: "mix", uzbek: "aralashtirmoq" },
  // { english: "stop", uzbek: "to'xtamoq" },
  // { english: "teach", uzbek: "o'qitmoq" },
  // { english: "concern", uzbek: "aloqada bo'lmoq" },
  // { english: "fly", uzbek: "uchmoq" },
  // { english: "born", uzbek: "tug'ulmoq" },
  // { english: "gain", uzbek: "foyda qilmoq" },
  // { english: "save", uzbek: "saqlamoq" },
  // { english: "stand", uzbek: "turmoq" },
  // { english: "fail", uzbek: "yiqilmoq" },
  // { english: "lead", uzbek: "olib bormoq" },
  // { english: "listen", uzbek: "tinglamoq" },
  // { english: "worry", uzbek: "xavotirlanmoq" },
  // { english: "express", uzbek: "ifodalamoq" },
  // { english: "handle", uzbek: "qo'lda tutmoq" },
  // { english: "meet", uzbek: "uchrashmoq" },
  // { english: "contribute", uzbek: "sadaqa qilmoq" },
  // { english: "consist", uzbek: "iborat bo'lmoq" },
  // { english: "release", uzbek: "ozod qilmoq" },
  // { english: "sell", uzbek: "sotmoq" },
  // { english: "finish", uzbek: "tugatmoq" },
  // { english: "press", uzbek: "nashr qilmoq" },
  // { english: "ride", uzbek: "minmoq" },
  // { english: "spread", uzbek: "sochmoq" },
  // { english: "spring", uzbek: "sapchimoq" },
  // { english: "wait", uzbek: "kutmoq" },
  // { english: "display", uzbek: "namoish qilmoq" },
  // { english: "flow", uzbek: "ergashmoq" },
  // { english: "hit", uzbek: "tepmoq" },
  // { english: "shoot", uzbek: "otmoq" },
  // { english: "touch", uzbek: "ushlamoq" },
  // { english: "cancel", uzbek: "bekor qilmoq" },
  // { english: "cry", uzbek: "yig'lamoq" },
  // { english: "dump", uzbek: "uymoq" },
  // { english: "push", uzbek: "itarmoq" },
  // { english: "select", uzbek: "tanlamoq" },
  // { english: "conflict", uzbek: "zid kelmoq" },
  // { english: "die", uzbek: "o'lmoq" },
  // { english: "eat", uzbek: "yemoq" },
  // { english: "fill", uzbek: "to'ldirmoq" },
  // { english: "jump", uzbek: "sakramoq" },
  // { english: "kick", uzbek: "yechmoq" },
  // { english: "pass", uzbek: "uzatmoq" },
  // { english: "pitch", uzbek: "palatka tikmoq" },
  // { english: "treat", uzbek: "davolamoq" },
  // { english: "abuse", uzbek: "suistemoq qilmoq" },
  // { english: "beat", uzbek: "urmoq" },
  // { english: "burn", uzbek: "kuymoq" },
  // { english: "deposit", uzbek: "bankka pul qo'ymoq" },
  // { english: "print", uzbek: "nashr qilmoq" },
  // { english: "raise", uzbek: "ko'tarmoq" },
  // { english: "sleep", uzbek: "uxlamoq" },
  // { english: "advance", uzbek: "odinga yurmoq" },
  // { english: "connect", uzbek: "ulanmoq" },
  // { english: "join", uzbek: "qatnashmoq" },
  // { english: "kill", uzbek: "o'ldirmoq" },
  // { english: "sit", uzbek: "o'tirmoq" },
  // { english: "tap", uzbek: "teginmoq" },
  // { english: "win", uzbek: "yutmoq" },
  // { english: "attack", uzbek: "xujum qilmoq" },
  // { english: "claim", uzbek: "davo qirmoq" },
  // { english: "drop", uzbek: "tomchilamoq" },
  // { english: "drink", uzbek: "ichmoq" },
  // { english: "guess", uzbek: "taxmin qilmoq" },
  // { english: "pull", uzbek: "tortmoq" },
  // { english: "wear", uzbek: "kiymoq" },
  // { english: "wonder", uzbek: "xayron qolmoq" },
  // { english: "count", uzbek: "xisoblamoq" },
  // { english: "doubt", uzbek: "shubha qilmoq" },
  // { english: "feed", uzbek: "boqmoq" },
  // { english: "impress", uzbek: "tassurot qoldirmoq" },
  // { english: "repeat", uzbek: "takrorlamoq" },
  // { english: "seek", uzbek: "qidirishmoq" },
  // { english: "sing", uzbek: "kuylamoq" },
  // { english: "slide", uzbek: "bo'lmoq" },
  // { english: "strip", uzbek: "shilmoq" },
  // { english: "wish", uzbek: "orzu qilmoq" },
  // { english: "collect", uzbek: "to'plamoq" },
  // { english: "combine", uzbek: "birlashtirmoq" },
  // { english: "command", uzbek: "buyruq bermoq" },
  // { english: "dig", uzbek: "qozmoq" },
  // { english: "divide", uzbek: "bo'lmoq" },
  // { english: "hang", uzbek: "osmoq" },
  // { english: "hunt", uzbek: "ov qilmoq" },
  // { english: "march", uzbek: "norozilik yurish qirmoq" },
  // { english: "mention", uzbek: "eslatib o'tmoq" },
  // { english: "smell", uzbek: "xidlamoq" },
  // { english: "survey", uzbek: "ko'z tashlamoq" },
  // { english: "tie", uzbek: "bog'lamoq" },
  // { english: "escape", uzbek: "qochmoq" },
  // { english: "expose", uzbek: "fosh qilmoq" },
  // { english: "gather", uzbek: "yig'moq" },
  // { english: "hate", uzbek: "nafratlanmoq" },
  // { english: "repair", uzbek: "tamirlamoq" },
  // { english: "scratch", uzbek: "tirnamoq" },
  // { english: "strike", uzbek: "xujum qilmoq" },
  // { english: "visit", uzbek: "tashrif buyurmoq" },
  // { english: "employ", uzbek: "ish bermoq" },
  // { english: "hurt", uzbek: "jarohatlanmoq" },
  // { english: "laugh", uzbek: "kulmoq" },
  // { english: "lay", uzbek: "yotqizmoq" },
  // { english: "respond", uzbek: "javob bermoq" },
  // { english: "split", uzbek: "tilamoq" },
  // { english: "strain", uzbek: "kuchlanmoq" },
  // { english: "struggle", uzbek: "kurashmoq" },
  // { english: "swim", uzbek: "suzmoq" },
  // { english: "train", uzbek: "tarbiyalamoq" },
  // { english: "wash", uzbek: "yuvmoq" },
  // { english: "waste", uzbek: "isrof qilmoq" },
  // { english: "convert", uzbek: "aylantirmoq" },
  // { english: "crash", uzbek: "halokatga uchramoq" },
  // { english: "fold", uzbek: "taxlamoq" },
  // { english: "grab", uzbek: "yulib olmoq" },
  // { english: "hide", uzbek: "yashirmoq" },
  // { english: "miss", uzbek: "sog'inmoq" },
  // { english: "permit", uzbek: "ruxsat bermoq" },
  // { english: "quote", uzbek: "dalil keltirmoq" },
  // { english: "recover", uzbek: "tiklamoq" },
  // { english: "resolve", uzbek: "hal qilmoq" },
  // { english: "roll", uzbek: "dumalamoq" },
  // { english: "sink", uzbek: "cho'kmoq" },
  // { english: "slip", uzbek: "toymoq" },
  // { english: "suspect", uzbek: "gumon qilinmoq" },
  // { english: "swing", uzbek: "belamoq" },
  // { english: "twist", uzbek: "qayrilmoq" },
  // { english: "concentrate", uzbek: "fikrini jamlamoq" },
  // { english: "estimate", uzbek: "baxolamoq" },
  // { english: "prompt", uzbek: "undamoq" },
  // { english: "refuse", uzbek: "rad etmoq" },
  // { english: "regret", uzbek: "afsuslanmoq" },
  // { english: "reveal", uzbek: "oshkor qilmoq" },
  // { english: "rush", uzbek: "shoshilmoq" },
  // { english: "shake", uzbek: "silkitmoq" },
  // { english: "shift", uzbek: "surmoq" },
  // { english: "shine", uzbek: "charaqlamoq" },
  // { english: "steal", uzbek: "o'g'irlamoq" },
  // { english: "surround", uzbek: "o'rab olmoq" },
  // { english: "bear", uzbek: "suyab turmoq" },
  // { english: "dare", uzbek: "davat qilmoq" },
  // { english: "delay", uzbek: "kechiktirmoq" },
  // { english: "hurry", uzbek: "shoshilmoq" },
  // { english: "invite", uzbek: "taklif qilmoq" },
  // { english: "kiss", uzbek: "o'pmoq" },
  // { english: "marry", uzbek: "uylanmoq" },
  // { english: "pop", uzbek: "qo'ymoq" },
  // { english: "pray", uzbek: "ibodat qilmoq" },
  // { english: "pretend", uzbek: "mug'ambirlik qilmoq" },
  // { english: "punch", uzbek: "mushlashmoq" },
  // { english: "quit", uzbek: "to'xtatmoq" },
  // { english: "reply", uzbek: "javob bermoq" },
  // { english: "resist", uzbek: "qarshilik ko'rsatmoq" },
  // { english: "rip", uzbek: "yirtmoq" },
  // { english: "rub", uzbek: "surtmoq" },
  // { english: "smile", uzbek: "jilmaymoq" },
  // { english: "spell", uzbek: "xarflamoq" },
  // { english: "stretch", uzbek: "cho'zilmoq" },
  // { english: "tear", uzbek: "yirtmoq" },
  // { english: "wake", uzbek: "uyg'onmoq" },
  // { english: "wrap", uzbek: "o'ramoq" },
  // { english: "like", uzbek: "yoqmoq" },
  // { english: "even", uzbek: "xato" },
  // { english: "film", uzbek: "kinoga tushmoq" },
  // { english: "water", uzbek: "sug'ormoq" },
  // { english: "been", uzbek: "bo'lmoq" },
  // { english: "well", uzbek: "qalqib chiqmoq" },
  // { english: "were", uzbek: "bo'lgan edi" },
  // { english: "example", uzbek: "misol keltirmoq" },
  // { english: "own", uzbek: "ega bo'lmoq" },
  // { english: "study", uzbek: "ta'lim olmoq" },
  // { english: "must", uzbek: "kerak bo'lmoq" },
  // { english: "form", uzbek: "tuzmoq" },
  // { english: "air", uzbek: "qurutmoq" },
  // { english: "place", uzbek: "joylashtirmoq" },
  // { english: "number", uzbek: "raqamlamoq" },
  // { english: "part", uzbek: "ajratmoq" },
  // { english: "field", uzbek: "maydonga tushmoq" },
  // { english: "fish", uzbek: "baliq ovlamoq" },
  // { english: "give", uzbek: "bermoq" },
  // { english: "heat", uzbek: "isitmoq" },
  // { english: "hand", uzbek: "uzatmoq" },
  // { english: "experience", uzbek: "tajriba qilmoq" },
  // { english: "dry", uzbek: "qurumoq" },
  // { english: "book", uzbek: "band qilmoq" },
  // { english: "end", uzbek: "tugatmoq" },
  // { english: "point", uzbek: "ko'rsatmoq" },
  // { english: "type", uzbek: "yozmoq" },
  // { english: "value", uzbek: "qiymat bermoq" },
  // { english: "clean", uzbek: "tozalamoq" },
  // { english: "market", uzbek: "sotmoq" },
  // { english: "guide", uzbek: "yo'l ko'rsatmoq" },
  // { english: "interest", uzbek: "qiziqmoq" },
  // { english: "state", uzbek: "bildirmoq" },
  // { english: "take", uzbek: "olmoq" },
  // { english: "speak", uzbek: "gapirmoq" },
  // { english: "break", uzbek: "sindirmoq" },
  // { english: "price", uzbek: "baxolamoq" },
  // { english: "size", uzbek: "tasavvur qilmoq" },
  // { english: "eat", uzbek: "yemoq" },
  // { english: "list", uzbek: "ro'yxatga kiritmoq" },
  // { english: "mind", uzbek: "fikirlamoq" },
  // { english: "trade", uzbek: "savdo qilmoq" },
  // { english: "line", uzbek: "ichini qoplamoq" },
  // { english: "care", uzbek: "g'amxorlik qilmoq" },
  // { english: "group", uzbek: "guruhlamoq" },
  // { english: "risk", uzbek: "tavakkal qilmoq" },
  // { english: "open", uzbek: "ochmoq" },
  // { english: "force", uzbek: "majburlamoq" },
  // { english: "light", uzbek: "yoritmoq" },
  // { english: "name", uzbek: "ism qo'ymoq" },
  // { english: "break", uzbek: "sindirmoq" },
  // { english: "amount", uzbek: "xosil bo'lmoq" },
  // { english: "order", uzbek: "buyurmoq" },
  // { english: "practice", uzbek: "mashq qilmoq" },
  // { english: "research", uzbek: "izlanish qilmoq" },
  // { english: "sense", uzbek: "tuymoq" },
  // { english: "service", uzbek: "xizmat qilmoq" },
  // { english: "choose", uzbek: "tanlamoq" },
  // { english: "enter", uzbek: "kirmoq" },
  // { english: "boss", uzbek: "xo'jayinlik qilmoq" },
  // { english: "win", uzbek: "yutmoq" },
  // { english: "page", uzbek: "chaqirmoq" },
  // { english: "term", uzbek: "atamoq" },
  // { english: "test", uzbek: "test qilmoq" },
  // { english: "answer", uzbek: "javob bermoq" },
  // { english: "sound", uzbek: "eshtilmoq" },
  // { english: "focus", uzbek: "etibor qilmoq" },
  // { english: "matter", uzbek: "muhim bo'lmoq" },
  // { english: "soil", uzbek: "kir qilmoq" },
  // { english: "board", uzbek: "aftobusga chiqmoq" },
  // { english: "oil", uzbek: "yog'lamoq" },
  // { english: "picture", uzbek: "tasavvur qilmoq" },
  // { english: "access", uzbek: "kirmoq" },
  // { english: "garden", uzbek: "bog'da ishlamoq" },
  // { english: "open", uzbek: "ochmoq" },
  // { english: "range", uzbek: "miqdor bermoq" },
  // { english: "rate", uzbek: "jalb qilmoq" },
  // { english: "reason", uzbek: "sabab" },
  // { english: "accord", uzbek: "ko'rsatmoq" },
  // { english: "site", uzbek: "joylashtirmoq" },
  // { english: "demand", uzbek: "talab qilmoq" },
  // { english: "exercise", uzbek: "mashq qilmoq" },
  // { english: "image", uzbek: "tasvirlamoq" },
  // { english: "case", uzbek: "sabab qilmoq" },
  // { english: "cause", uzbek: "sabab qilmoq" },
  // { english: "agree", uzbek: "rozi bo'lmoq" },
  // { english: "arrive", uzbek: "yetib kelmoq" },
  // { english: "attack", uzbek: "xujum qilmoq" },
  // { english: "result", uzbek: "natija ko'rsatmoq" },
  // { english: "hide", uzbek: "yashirmoq" },
  // { english: "build", uzbek: "qurmoq" },
  // { english: "hunt", uzbek: "ov qilmoq" },
  // { english: "cash", uzbek: "naxt to'lamoq" },
  // { english: "class", uzbek: "sinflamoq" },
];
